var fund = {
    ch: {
        sdata: [{
            comp: 4,
            cate: 7,
            risk: 4,
            name: '富国天益价值混合型证券投资基金',
            id: 13
        }, {
            comp: 4,
            cate: 7,
            risk: 3,
            name: '富国天成红利灵活配置混合型证券投资基金',
            id: 14
        }, {
            comp: 4,
            cate: 7,
            risk: 4,
            name: '富国天惠精选成长混合型证券投资基金（LOF）',
            id: 2021
        }, {
            comp: 4,
            cate: 7,
            risk: 4,
            name: '富国天合稳健优选混合型证券投资基金',
            id: 11
        }, {
            comp: 4,
            cate: 4,
            risk: 2,
            name: '富国天利增长债券投资基金',
            id: 12
        }, {
            comp: 4,
            cate: 7,
            risk: 4,
            name: '富国天博创新主题混合型证券投资基金',
            id: 2020
        }, {
            comp: 2,
            cate: 3,
            risk: 4,
            name: '景顺长城量化精选股票型证券投资基金',
            id: 4030
        }, {
            comp: 2,
            cate: 3,
            risk: 3,
            name: '景顺长城沪深300指数增强型证券投资基金',
            id: 4029
        }, {
            comp: 2,
            cate: 7,
            risk: 3,
            name: '景顺长城动力平衡证券投资基金 ',
            id: 8
        }, {
            comp: 2,
            cate: 7,
            risk: 4,
            name: '景顺长城核心竞争力混合型证券投资基金',
            id: 3023
        }, {
            comp: 2,
            cate: 7,
            risk: 4,
            name: '景顺长城内需增长混合型证券投资基金',
            id: 1
        }, {
            comp: 2,
            cate: 7,
            risk: 4,
            name: '景顺长城内需增长贰号混合型证券投资基金',
            id: 2
        }, {
            comp: 2,
            cate: 7,
            risk: 3,
            name: '景顺长城能源基建混合型证券投资基金',
            id: 5
        }, {
            comp: 2,
            cate: 7,
            risk: 4,
            name: '景顺长城优选混合型证券投资基金',
            id: 4
        }, {
            comp: 2,
            cate: 6,
            risk: 1,
            name: '景顺长城货币市场证券投资基金A',
            id: 9
        }, {
            comp: 2,
            cate: 6,
            risk: 1,
            name: '景顺长城货币市场证券投资基金B',
            id: 10
        }, {
            comp: 2,
            cate: 7,
            risk: 3,
            name: '景顺长城资源垄断混合型证券投资基金（LOF） ',
            id: 2022
        }, {
            comp: 3,
            cate: 7,
            risk: 3,
            name: '泰达宏利价值优化型稳定类行业混合型证券投资基金',
            id: 7
        }, {
            comp: 3,
            cate: 7,
            risk: 3,
            name: '泰达宏利行业精选混合型证券投资基金',
            id: 6
        }, {
            comp: 5,
            cate: 6,
            risk: 1,
            name: '上投摩根货币市场基金',
            id: 1013
        }, {
            comp: 5,
            cate: 7,
            risk: 3,
            name: '上投摩根双核平衡混合型证券投资基金',
            id: 1020
        }, {
            comp: 5,
            cate: 4,
            risk: 2,
            name: '上投摩根分红添利债券型证券投资基金A',
            id: 1021
        }, {
            comp: 5,
            cate: 7,
            risk: 4,
            name: '上投摩根新兴动力混合型证券投资基金',
            id: 3021
        }, {
            comp: 5,
            cate: 7,
            risk: 4,
            name: '上投摩根行业轮动混合型证券投资基金',
            id: 3022
        }, {
            comp: 6,
            cate: 7,
            risk: 4,
            name: '海富通收益增长证券投资基金',
            id: 1014
        }, {
            comp: 6,
            cate: 7,
            risk: 4,
            name: '海富通股票混合型证券投资基金',
            id: 1015
        }, {
            comp: 6,
            cate: 7,
            risk: 4,
            name: '海富通精选证券投资基金',
            id: 1016
        }, {
            comp: 6,
            cate: 7,
            risk: 4,
            name: '海富通风格优势混合型证券投资基金',
            id: 1017
        }, {
            comp: 6,
            cate: 6,
            risk: 2,
            name: '海富通货币市场证券投资基金A',
            id: 1018
        }, {
            comp: 6,
            cate: 6,
            risk: 2,
            name: '海富通货币市场证券投资基金B',
            id: 1019
        }, {
            comp: 7,
            cate: 6,
            risk: 2,
            name: '博时现金收益证券投资基金A',
            id: 4023
        }, {
            comp: 7,
            cate: 7,
            risk: 3,
            name: '博时主题行业混合型证券投资基金(LOF)',
            id: 4022
        }, {
            comp: 7,
            cate: 7,
            risk: 4,
            name: '博时平衡配置混合型证券投资基金',
            id: 4021
        }, {
            comp: 8,
            cate: 7,
            risk: 4,
            name: '华夏兴华混合型证券投资基金',
            id: 4024
        }, {
            comp: 12,
            cate: 7,
            risk: 4,
            name: '中欧医疗健康混合型证券投资基金A',
            id: 4027
        }],
        13: {
            name: '富国天益价值混合型证券投资基金',
            code: '100020',
            cate: '混合型',
            comp: '富国基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/hunhe/100029/\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/hunhe/100020\');">点击查看</a>',
            date: '2004年06月15日',
            risk: '4',
            rate: 'http://www.fullgoal.com.cn/funds/hunhe/100020/index.html?statistics_type=$fundsMiddle$',
            share: '现金分红',
            intro: 'fuguojijinguanli.htm',
            target: '本基金属价值型证券投资基金，主要投资于内在价值被低估的上市公司的股票，或与同类型上市公司相比具有更高相对价值的上市公司的股票。本基金通过对投资组合的动态调整来分散和控制风险，在注重基金资产安全的前提下，追求基金资产的长期稳定增值。',
            feature: '较高风险',
            standard: '沪深300指数收益率×95%+中债综合全价指数收益率×5%',
            range: '本基金投资范围包括国内依法公开发行、上市的股票和债券以及中国证监会允许基金投资的其它金融工具。',
            tactics: '本基金采取积极的投资策略。本基金在大类资产配置和行业配置层面，遵循自上而下的积极策略，个股选择层面，遵循自下而上的积极策略。根据基金经理对股票市场变动的趋势的判断，决定基金资产在股票、债券、现金等金融资产上的分布以及股票组合的行业比例配置，并进行动态配比以规避系统性风险的影响，最大限度地确保基金资产的安全。在遵循既定的资产配置方针的前提下，基金经理和行业分析师结合对行业和上市公司的研究和调研，筛选投资目标股。基金经理决定投资目标股的组合权重，并负责对组合进行动态的调整和优化。在目前中国债券市场处于制度与规则快速调整的阶段，管理人将采用久期控制下的主动性投资策略，主要包括：久期控制、期限结构配置、市场转换和相对价值判断等管理手段。在有效控制整体资产风险的基础上，根据对宏观经济发展状况、金融市场运行特点等因素的分析确定组合整体框架；对债券市场、收益率曲线以及各种债券品种价格的变化进行预测，相机而动、积极调整',
            notice: 'http://www.fullgoal.com.cn/funds/hunhe/100020/report/index.html',
            record: 'dailylmfnav',
            agreement: 'FuGuoTianYiJiaZhiJiJinHeTong',
            investmentcontract: 'http://www.fullgoal.com.cn/funds/hunhe/100020/report/index.html',
            instruction: 'http://www.fullgoal.com.cn/funds/hunhe/100020/index.html?statistics_type=$fundsMiddle$',
            protocol: 'FuGuoTianYiJiaZhiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        14: {
            name: '富国天成红利灵活配置混合型证券投资基金',
            code: '100029',
            cate: '混合型',
            comp: '富国基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/hunhe/100029/\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/hunhe/100029/\');">点击查看</a>',
            date: '2008年05月28日',
            risk: '3',
            rate: 'http://www.fullgoal.com.cn/funds/hunhe/100029/index.html?statistics_type=$fundsMiddle$',
            share: '现金分红',
            intro: 'fuguojijinguanli.htm',
            target: '主要投资于红利型股票与稳健成长型股票，兼顾红利收益与资本增值；力争通过灵活合理的大类资产配置与专业的个券精选，在精细化风险管理的基础上构建优化组合，谋求基金资产的长期稳定增值。',
            feature: '中等风险',
            standard: '沪深300指数收益率×55%+中债综合全价指数收益率×45%',
            range: '本基金的投资范围为具有良好流动性的金融工具，包括国内依法公开发行上市的股票、债券、权证以及中国证监会允许基金投资的其他金融工具或金融衍生工具。如法律法规或监管机构以后允许基金投资的其他品种，基金管理人在履行适当程序后，可以将其纳入投资范围。',
            tactics: '本基金将采用“自上而下”与“自下而上”相结合的主动投资管理策略，将定性分析与定量分析贯穿于资产配置、行业细分、公司价值评估以及组合风险管理全过程中。',
            notice: 'http://www.fullgoal.com.cn/funds/hunhe/100029/report/index.html',
            record: 'dailylmfnav',
            agreement: 'FuGuoTianChengHongLiLingHuoPeiZhiJiJinHeTong',
            investmentcontract: 'http://www.fullgoal.com.cn/funds/hunhe/100029/report/index.html',
            instruction: 'http://www.fullgoal.com.cn/funds/hunhe/100029/index.html?statistics_type=$fundsMiddle$',
            protocol: 'FuGuoTianChengHongLiLingHuoPeiZhiTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        2021: {
            name: '富国天惠精选成长混合型证券投资基金（LOF）',
            code: '161005',
            cate: '混合型',
            comp: '富国基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/hunhe/161005/\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/hunhe/161005/\');">点击查看</a>',
            date: '2005年11月16日',
            risk: '4',
            rate: 'http://www.fullgoal.com.cn/funds/hunhe/161005/index.html?statistics_type=$fundsMiddle$',
            share: '现金分红',
            intro: 'fuguojijinguanli.htm',
            target: '本基金主要投资于具有良好成长性且合理定价的股票，在利用金融工程技术控制组合风险的前提下，谋求基金资产的长期最大化增值。',
            feature: '本基金是一只主动投资的混合型基金，主要投资于具有良好成长性且合理定价的股票，风险和预期收益匹配，属于风险适中的证券投资基金品种。本基金力争在严格控制风险的前提下谋求实现基金资产长期稳定增长。',
            standard: '沪深300指数收益率×70%+中债综合全价指数收益率×25%+同业存款利率×5%',
            range: '本基金的投资范围为具有良好流动性的金融工具，包括国内依法公开发行上市的股票、债券以及中国证监会允许基金投资的其他金融工具，其中债券部分包括国债、金融债、企业（公司）债（包括可转债）以及中国证监会允许基金投资的其他债券。基金股票部分主要投资于具有良好成长性且合理定价的上市公司股票。该类股票应具体满足以下特征：<br>1、预期当年净利润增长率（预期当年主营业务收入增长率）在全部上市公司中由高到低排名，位于前1/3部分的股票；<br>2、基于“富国成长性股票价值评估体系”，在全部上市公司中成长性和投资价值排名前10%的股票。',
            tactics: '1、资产配置<br>（1）本基金在对宏观经济、政策环境、利率走势、资金供给以及证券市场的现状及发展趋势等因素进行深入分析研究的基础上，动态配置股票、债券、现金之间比例；<br>（2）应用量化工具，在综合考虑资产组合的风险、收益、流动性、各类资产相关性等因素的基础上，对上述资产配置比例进行二次优化，以求最大限度规避风险；<br>（3）在正常市场状况下，本基金投资组合中的股票投资比例浮动范围为：50%-95%；债券和短期金融工具的投资比例浮动范围为：5%-50%,其中现金或者到期日在一年以内的政府债券的比例不低于5%。投资于具有良好成长性且合理定价的上市公司股票的比例不低于基金股票投资的80%。<br>2、股票投资策略<br>在股票投资层面，本基金采用主动投资管理策略，基于“快速成长、合理定价”的选股标准精选个股，并在坚持以基本面研究驱动投资的基础上进行适度的选时操作，争取投资收益的最大化。<br>（1）精选个股，构建富国“G.D.P.真钻投资组合”（G.D.P.－Genuine Diamond Portfolio）：<br>本基金管理人借鉴外方股东加拿大蒙特利尔银行金融集团（BMO Financial Group）的投资管理经验及技能，结合国内市场的特征，应用“富国成长性股票价值评估体系”，将定性分析和定量分析相结合，筛选出具有成长潜力且合理定价的上市公司股票，构建富国“G.D.P.真钻投资组合”（G.D.P.－Genuine Diamond Portfolio）：<br>“富国成长性股票价值评估体系”重点关注的股票库：<br>本基金认为，在整个市场具有绝对投资价值的前提下，达到以下量化选择标准的股票将是本基金重点关注的对象：<br>【1】、预期当年净利润增长率（预期当年主营业务收入增长率）在全部上市公司中由高到低排名，位于前1/3部分的股票；<br>【2】、动态市盈率（动态市盈率＝总市值/预期的当年净利润）在全部上市公司中由低到高排名，位于前1/3部分的股票。<br>“富国成长性股票价值评估体系”重点关注的因素：<br>【1】、行业周期（公司成长的环境）。企业所在行业处于发展期、成熟期前期或者正从衰退中复苏；<br>【1】、行业周期（公司成长的环境）。企业所在行业处于发展期、成熟期前期或者正从衰退中复苏；【2】、市场容量（公司成长的空间）。企业主营业务收入来源所在的市场空间较大且需求持续增长；<br>【3】、生产销售优势（公司成长的加速度）。企业在资源配置、产能扩张、销售网络、销售能力、市场知名度和品牌效应等方面具有独特优势，企业借此优势可不断提高市场占有率；<br>【4】、技术因素（公司成长的原动力）。企业的研发能力和学习能力较强且具有一定的持续性，企业在产品开发、技术进步、专利储备等方面具有较强的核心竞争力；<br>【5】、制度因素（公司成长的最终解释力）。企业管理能力较强，管理制度健全兼具创新性，内部治理结构完善；<br>【6】、并购因素（公司成长的全新推动力）。企业存在潜在发生重组、收购、兼并的可能性或机会，并可能明显改善企业的盈利能力；<br>【7】、财务状况（公司稳健成长的保证）。企业财务状况良好，资产结构合理，偿付能力较强、成本控制能力突出，净收益增长率较快，股权回报率较高；<br>【8】、股价表现（公司成长的公允表现）。综合考虑股价历史表现、国内和国外定价水平等因素，重点关注相对定价合理的成长型企业。<br>（2）适度选时操作：<br>本基金将运用富国市场预测模型、趋势识别及确认模型，在基于两种模型互相确认的基础上，在合理范围内进行适度的时机选择操作。<br>3、债券投资策略<br>在目前中国债券市场处于制度与规则快速调整的阶段，本基金将采用久期控制下的主动性投资策略，主要包括：久期控制、期限结构配置、市场转换、相对价值判断和信用风险评估等管理手段。在有效控制整体资产风险的基础上，根据对宏观经济发展状况、金融市场运行特点等因素的分析确定组合整体框架；对债券市场、收益率曲线以及各种债券品种价格的变化进行预测，相机而动、积极调整。<br>【1】、久期控制是根据对宏观经济发展状况、金融市场运行特点等因素的分析确定组合的整体久期，有效的控制整体资产风险；<br>【2】、期限结构配置是在确定组合久期后，针对收益率曲线形态特征确定合理的组合期限结构，包括采用集中策略、两端策略和梯形策略等，在长期、中期和短期债券间进行动态调整，从长、中、短期债券的相对价格变化中获利；<br>【3】、市场转换是指管理人将针对债券子市场间不同运行规律和风险－收益特性构建和调整组合，提高投资收益；<br>【4】、相对价值判断是在现金流特征相近的债券品种之间选取价值相对低估的债券品种，选择合适的交易时机，增持相对低估、价格将上升的类属，减持相对高估、价格将下降的类属；<br>【5】、信用风险评估是指管理人将充分利用现有行业与公司研究力量，根据发债主体的经营状况和现金流等情况对其信用风险进行评估，以此作为品种选择的基本依据。',
            notice: 'http://www.fullgoal.com.cn/funds/hunhe/161005/report/index.html',
            record: 'dailylmfnav',
            agreement: 'FuGuoTianHuiJingXuanChengZhangJiJinHeTong',
            investmentcontract: 'http://www.fullgoal.com.cn/funds/hunhe/161005/report/index.html',
            instruction: 'http://www.fullgoal.com.cn/funds/hunhe/161005/index.html?statistics_type=$fundsMiddle$',
            protocol: 'FuGuoTianHuiJingXuanChengZhangTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        11: {
            name: '富国天合稳健优选混合型证券投资基金',
            code: '100026',
            cate: '混合型',
            comp: '富国基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/hunhe/100026/\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/hunhe/100026/\');">点击查看</a>',
            date: '2006年11月15日',
            risk: '4',
            rate: 'http://www.fullgoal.com.cn/funds/hunhe/100026/index.html?statistics_type=$fundsMiddle$',
            share: '现金分红',
            intro: 'fuguojijinguanli.htm',
            target: '本基金主要采用“核心－卫星”总体策略，以优选并复制绩优基金重仓股为基石，有效综合基金管理人的主动投资管理能力，力争投资业绩实现基金行业平均水平之上的二次超越，谋求基金资产的长期最大化增值。',
            feature: '较高风险',
            standard: '沪深300指数收益率×80%+中债综合全价指数收益率×15%+同业存款利率×5%',
            range: '本基金的投资范围为具有良好流动性的金融工具，包括国内依法公开发行上市的股票、债券以及中国证监会允许基金投资的其他金融工具，其中债券部分包括国债、金融债、企业（公司）债（包括可转债）以及中国证监会允许基金投资的其他债券。如法律法规或监管机构以后允许基金投资的其他品种，基金管理人在履行适当程序后，可以将其纳入投资范围。',
            tactics: '本基金诉求“三重优化”概念，通过优选基金、（构建）优选指数、优选个股进行投资操作，将主动管理与被动跟踪有效结合，力争实现稳健投资业绩基础上的“二次超越”。',
            notice: 'http://www.fullgoal.com.cn/funds/hunhe/100026/report/index.html',
            record: 'dailylmfnav',
            agreement: 'FuGuoWenJianYouXuanJiJinHeTong',
            investmentcontract: 'http://www.fullgoal.com.cn/funds/hunhe/100026/report/index.html',
            instruction: 'http://www.fullgoal.com.cn/funds/hunhe/100026/index.html?statistics_type=$fundsMiddle$',
            protocol: 'FuGuoWenJianYouXuanJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        12: {
            name: '富国天利增长债券投资基金',
            code: '100018',
            cate: '债券型',
            comp: '富国基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/zhaiquan/100018\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/zhaiquan/100018\');">点击查看</a>',
            date: '2003年12月02日',
            risk: '2',
            rate: 'http://www.fullgoal.com.cn/funds/zhaiquan/100018/index.html?statistics_type=$fundsMiddle$',
            share: '现金分红',
            intro: 'fuguojijinguanli.htm',
            target: '本基金为主要投资于高信用等级固定收益证券的投资基金，投资目标是在充分重视本金长期安全的前提下，力争为基金份额持有人创造较高的当期收益。',
            feature: '低风险',
            standard: '中债总指数',
            range: '本基金主要投资于固定收益类金融工具，包括国内依法公开发行、上市的国债、金融债、企业（公司）债、可转债，以及中国证监会允许基金投资的其他金融工具。本基金可以通过参与新股首发等低风险的投资方式来提高基金收益水平。',
            tactics: '本基金的投资策略将随市场效率的提高而调整。在目前中国债券市场处于制度与规则快速调整的阶段，管理人将采用久期控制下的主动性投资策略，主要包括：久期控制、期限结构配置、市场转换和相对价值判断等管理手段。在有效控制整体资产风险的基础上，根据对宏观经济发展状况、金融市场运行特点等因素的分析确定组合整体框架；对债券市场、收益率曲线以及各种债券品种价格的变化进行预测，相机而动、积极调整。<br>1、久期控制是根据对宏观经济发展状况、金融市场运行特点等因素的分析确定组合的整体久期，有效的控制整体资产风险；<br>2、信用风险管理方面管理人将充分利用现有行业与公司研究力量，根据发债主体的经营状况和现金流等情况对其信用风险进行评估，以此作为品种选择的基本依据。<br>3、期限结构配置是在确定组合久期后，针对收益率曲线形态特征确定合理的组合期限结构，包括采用集中策略、两端策略和梯形策略等，在长期、中期和短期债券间进行动态调整，从长、中、短期债券的相对价格变化中获利。<br>4、市场转换是指管理人将针对债券子市场间不同运行规律和风险特性构建和调整组合，提高投资收益。<br>5、相对价值判断是在现金流特征相近的债券品种之间选取价值相对低估的债券品种，选择合适的交易时机，增持相对低估、价格将上升的类属，减持相对高估、价格将下降的类属。<br>主动性投资策略的制定与贯彻的过程，也是管理人对于风险进行动态评估与管理的过程。对风险定价失效机会的把握充分体现了主动性投资策略的特点。在系统化的风险控制体系下，通过对管理指标的设定与监控，管理人不但可以有效控制整体资产的风险水平，而且可以在寻求风险结构优化的过程中不断提高基金的收益水平。',
            notice: 'http://www.fullgoal.com.cn/funds/zhaiquan/100018/report/index.html',
            record: 'dailylmfnav',
            agreement: 'FuGuoTianLiZengZhangJiJinHeTong',
            investmentcontract: 'http://www.fullgoal.com.cn/funds/zhaiquan/100018/report/index.html',
            instruction: 'http://www.fullgoal.com.cn/funds/zhaiquan/100018/index.html?statistics_type=$fundsMiddle$',
            protocol: 'FuGuoTianLiZengZhangJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        2020: {
            name: '富国天博创新主题混合型证券投资基金',
            code: '519035',
            cate: '混合型',
            comp: '富国基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/hunhe/519035/\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fullgoal.com.cn/funds/hunhe/519035/\');">点击查看</a>',
            date: '2007年04月27日',
            risk: '4',
            rate: 'http://www.fullgoal.com.cn/funds/hunhe/519035/index.html?statistics_type=$fundsMiddle$',
            share: '现金分红',
            intro: 'fuguojijinguanli.htm',
            target: '本基金主要投资于具有良好成长性的创新主题类上市公司，在充分注重投资组合收益性、流动性与安全性的基础上，力争实现资本的长期稳定增值。',
            feature: '本基金是一只主动投资的证券投资基金，属于较高预期收益、较高预期风险的证券投资基金品种。',
            standard: '沪深300指数收益率×80%+中债综合全价指数收益率×15%+同业存款利率×5%',
            range: '本基金的投资范围为具有良好流动性的金融工具，包括国内依法公开发行上市的股票、债券、权证以及中国证监会允许基金投资的其他金融工具。<br>如法律法规或监管机构以后允许基金投资的其他品种，基金管理人在履行适当程序后，可以将其纳入投资范围。',
            tactics: '本基金将采用“自上而下”与“自下而上”相结合的主动投资管理策略，将定性分析与定量分析贯穿于资产配置、行业细分、个券选择以及组合风险管理全过程中。<br>1、资产配置<br>（1）本基金基于对宏观面、政策面、基本面和资金面等四个角度的综合分析，充分研判各类资产的风险、收益、流动性及相关性等因素，灵活配置大类资产，力求减小投资组合的系统性风险。<br>（2）本基金投资的资产类别包括股票、债券、权证等。其中，股票类资产包括上市公司流通股股票和未来可能出现的诸如中国预托凭证之类的股权类证券；债券类资产包括国债、金融债、企业债（包括可转债）、央行票据、资产支持证券、短期融资券、回购协议以及现金存款等。<br>在正常市场状况下，本基金投资组合中的股票投资比例浮动范围为：60%-95%；除股票以外的其他资产投资比例浮动范围为：5%－40%，其中现金或者到期日在一年以内的政府债券的比例不低于5%。其中，投资于创新主题类上市公司股票的比例不低于基金股票投资的80%。本基金定义的创新主题类上市公司为符合国家产业发展方向、在企业经营管理中知识与科技的运用对其发展有重要的推动作用、具备行业领先或技术领先优势的上市公司以及经重组后将显现上述特征的上市公司。<br>2、股票投资策略<br>基金管理人认为，当今时代，人类社会已经步入了一个创新不断涌现的重要时期，也步入了一个经济结构加快调整的重要时期。生产力、生产方式、生活方式和经济社会发展观在创新的推动下发生了前所未有的深刻变革，生产要素的流动与产业转移也在因创新而不断加快：信息科技创新已经成为推动经济增长和知识传播应用进程的重要引擎；生命科学和生物技术创新在对改善和提高人类生活质量方面发挥着关键作用；能源科技创新正在为进一步化解能源与环境问题开辟新途径；材料科技创新将带来深刻的技术变革，基础研究的重大突破逐渐为人类认知客观规律、推动技术和经济发展展现新的前景。在这样的大背景下，我国作出了建设创新型国家的决策，把增强自主创新能力作为国家战略，加强国家创新体系建设。<br>在资本市场上，由于创新主题类公司具有着强大的竞争优势，其公司业绩在未来较长的时间内将会保持持续高速的成长，股价也将相应地持续大幅升高。因此，本基金以创新主题类上市公司作为股票投资主体，在高度重视基本面分析的基础上遵循“关注成长，合理预期企业未来价值”的选股标准精选个股，力争为投资者带来丰厚的回报。<br>具体而言，本基金将通过成长性评估、价值评估、现金流预测与行业环境评估等多项指标全面考量公司的基本面，关注因素包括：行业竞争趋势、公司竞争地位、公司业务发展的关键点、短期与长期内公司现金流增长的主要驱动来源、公司治理结构等，运用的的分析模型包括自由现金流折现模型（DCF）、经济价值模型（EV/EBITDA）、杜邦财务分析模型（DuPont Analysis）等。在创新属性评估方面，本基金将重点考量创新的预期效果，并判断创新是否已经或者将会驱动企业的成长。本基金对创新的认定涵盖制度创新、技术创新、产品创新、服务创新、流程创新、管理模式创新、商业模式创新、需求创新等多个角度。其中，对于公司的具体创新项目，本基金将重点评价基于项目的预期投资回报率，具体衡量指标包括：销售收入边际增长率、毛利率边际增长率、净利率边际增长率、投入资本回报率等。<br>3、债券投资策略<br>在目前中国债券市场处于制度与规则快速调整的阶段，本基金将采用久期控制下的主动性投资策略，主要包括：久期控制、期限结构配置、市场转换、相对价值判断和信用风险评估等管理手段。在有效控制整体资产风险的基础上，根据对宏观经济发展状况、金融市场运行特点等因素的分析确定组合整体框架；对债券市场、收益率曲线以及各种债券品种价格的变化进行预测，相机而动、积极调整。<br>（1）久期控制是根据对宏观经济发展状况、金融市场运行特点等因素的分析确定组合的整体久期，有效的控制整体资产风险；<br>（2）期限结构配置是在确定组合久期后，针对收益率曲线形态特征确定合理的组合期限结构，包括采用集中策略、两端策略和梯形策略等，在长期、中期和短期债券间进行动态调整，从长、中、短期债券的相对价格变化中获利；<br>（3）市场转换是指管理人将针对债券子市场间不同运行规律和风险－收益特性构建和调整组合，提高投资收益；<br>（4）相对价值判断是在现金流特征相近的债券品种之间选取价值相对低估的债券品种，选择合适的交易时机，增持相对低估、价格将上升的类属，减持相对高估、价格将下降的类属；<br>（5）信用风险评估是指管理人将充分利用现有行业与公司研究力量，根据发债主体的经营状况和现金流等情况对其信用风险进行评估，以此作为品种选择的基本依据。<br>本基金将重点关注具有以下一项或者多项特征的债券：<br>（1）具有良好流动性的债券；<br>（2）具有较高信用等级的债券；<br>（3）在信用等级与剩余期限类似的条件下，到期收益率较高的债券；<br>（4）风险水平合理、有较好的下行保护且基本面有良性变化的可转换债券。<br>4、适时选择权证投资<br>本基金还可能运用基金财产进行权证投资。在权证投资过程中，基金管理人主要通过采取有效的组合策略，将权证作为风险管理及降低投资组合风险的工具：<br>（1）运用权证与标的资产可能形成的风险对冲功能，构建权证与标的股票的组合，主要通过波幅套利及风险对冲策略实现相对收益；<br>（2）构建权证与债券的组合，利用债券的固定收益特征和权证的高杠杆特性，形成保本投资组合；<br>（3）针对不同的市场环境，构建骑墙组合、扼制组合、蝶式组合等权证投资组合，形成多元化的盈利模式；<br>（4）在严格风险监控的前提下，通过对标的股票、波动率等影响权证价值因素的深入研究，谨慎参与以杠杆放大为目标的权证投资。',
            notice: 'http://www.fullgoal.com.cn/funds/gupiao/519035/base/ziliao/index.html',
            record: 'dailylmfnav',
            agreement: 'FuGuoTianBoChuangXinZhuTiJiJinHeTong',
            investmentcontract: 'http://www.fullgoal.com.cn/funds/hunhe/519035/report/index.html',
            instruction: 'http://www.fullgoal.com.cn/funds/hunhe/519035/index.html?statistics_type=$fundsMiddle$',
            protocol: 'FuGuoTianBoChuangXinZhuTiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        4030: {
            name: '景顺长城量化精选股票型证券投资基金',
            code: '000978',
            cate: '股票型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/000978/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/000978/detail.html\');">点击查看</a>',
            date: '2015年02月04日',
            risk: '4',
            rate: 'http://www.igwfmc.com/main/jjcp/product/000978/detail.html',
            share: '现金分红',
            intro: 'jingshunchangcheng.htm',
            target: '本基金通过量化模型精选股票，在有效控制风险的前提下，力争获取超越业绩比较基准的投资回报，谋求基金资产的长期增值。',
            feature: '本基金是一只股票型基金，属于较高预期风险、较高预期收益的证券投资基金品种，其预期风险与预期收益高于混合型基金、债券型基金与货币市场基金。',
            standard: '中证500指数收益率×95%+商业银行活期存款利率(税后)×5%',
            range: '80%-95% 投资于股票资产5%－20% 投资于除股票外的其他资产，其中权证资产占基金资产净值的比例范围为0－3%每个交易日日终在扣除股指期货合约需缴纳的交易保证金后，现金或到期日在一年以内的政府债券不低于基金资产净值的5%。',
            tactics: '本基金通过量化模型精选股票，在有效控制风险的前提下，力争获取超越业绩比较基准的投资回报，谋求基金资产的长期增值。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/000978/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengLiangHuaJiJinHeTong',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/000978/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/000978/detail.html',
            protocol: 'JingShunChangChengLiangHuaTuoGuanXieYi',
            remark: ''
        },
        4029: {
            name: '景顺长城沪深300指数增强型证券投资基金',
            code: '000311',
            cate: '股票型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/000311/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/000311/detail.html\');">点击查看</a>',
            date: '2013年10月29日',
            risk: '3',
            rate: 'http://www.igwfmc.com/main/jjcp/product/000311/detail.html',
            share: '现金分红',
            intro: 'jingshunchangcheng.htm',
            target: '本基金在力求有效跟踪标的指数，控制本基金的净值增长率与业绩比较基准之间的日均跟踪偏离度的绝对值不超过0.5%，年跟踪误差不超过7.75%的基础上，结合量化方法追求超越标的指数的业绩水平。',
            feature: '中风险',
            standard: '95%×沪深300指数收益率＋1.5%（指年收益率，评价时按期间折算）',
            range: '股票投资比例范围为基金资产的90%－95％，投资于标的指数成分股及其备选成分股的比例不低于非现金资产的80％，每个交易日日终在扣除股指期货保证金以后，本基金保留的现金或到期日在一年以内的政府债券投资比例不低于基金资产净值的5％',
            tactics: '本基金在力求有效跟踪标的指数，控制本基金的净值增长率与业绩比较基准之间的日均跟踪偏离度的绝对值不超过0.5%，年跟踪误差不超过7.75%的基础上，结合量化方法追求超越标的指数的业绩水平。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/000311/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengHuSheng300ZhiShuJiJinHeTong',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/000311/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/000311/detail.html',
            protocol: 'JingShunChangChengHuSheng300ZhiShuJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年3月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        8: {
            name: '景顺长城动力平衡证券投资基金',
            code: '260103',
            cate: '混合型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260103/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260103/detail.html\');">点击查看</a>',
            date: '2003年10月24日',
            risk: '3',
            rate: 'http://www.igwfmc.com/main/jjcp/product/260103/detail.html',
            share: '现金分红',
            intro: 'jingshunchangcheng.htm',
            target: '动力平衡基金以获取高于业绩比较基准的回报为目标，注重通过动态的资产配置以达到当期收益与长期资本增值的兼顾，争取为投资者提供长期稳定的回报',
            feature: '中等风险',
            standard: '沪深300指数收益率×50%＋中国债券总指数收益率×45%+银行同业存款收益率×5%',
            range: '景顺长城动力平衡基金将投资于股票、国债、金融债、企业（上市公司）债、可转换债及中国证监会批准的其他投资品种，或保持现金。',
            tactics: '通过在股票、债券和现金之间动态的资产配置来获得资本保全，并获得稳定的回报。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/260103/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengDongLiPingHengZhengQuanTouZiJiJinHeTong',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/260103/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/260103/detail.html',
            protocol: 'JingShunChangChengJingXiLieKaiFangShiZhengQuanTouZiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        3023: {
            name: '景顺长城核心竞争力混合型证券投资基金',
            code: '260116',
            cate: '混合型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260116/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260116/detail.html\');">点击查看</a>',
            date: '2011年12月20日',
            risk: '4',
            rate: 'http://www.igwfmc.com/main/jjcp/product/260116/detail.html',
            share: '现金分红',
            intro: 'jingshunchangcheng.htm',
            target: '本基金通过投资于具有投资价值的优质企业，分享其在中国经济增长的大背景下的可持续性增长，以实现基金资产的长期资本增值。',
            feature: '本基金为混合型基金产品，基金资产整体的预期收益和预期风险均较高，属于较高风险、较高收益的基金品种。',
            standard: '沪深300指数×80%＋中证全债指数×20%',
            range: '本基金将基金资产的60%-95%投资于股票等权益类资产（其中，权证投资比例不超过基金资产净值的3%），将基金资产的5%-40%投资于债券和现金等固定收益类品种（其中，现金或到期日在一年以内的政府债券不低于基金资产净值的5%）。',
            tactics: '我们将围绕代表中国经济转型方向的消费升级和产业结构升级领域，寻找具有核心竞争力的成长性好的公司进行投资。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/260116/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengHeXinJingZhengLiJiJinHeTong',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/260116/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/260116/detail.html',
            protocol: 'JingShunChangChengHeXinJingZhengLiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        1: {
            name: '景顺长城内需增长混合型证券投资基金',
            code: '260104',
            cate: '混合型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260104/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260104/detail.html\');">点击查看</a>',
            date: '2004年06月25日',
            risk: '4',
            rate: 'http://www.igwfmc.com/main/jjcp/product/260104/detail.html',
            share: '现金分红',
            intro: 'jingshunchangcheng.htm',
            target: '本基金通过优先投资于内需拉动型行业，分享中国经济和行业的快速增长带来的最大收益，实现基金资产的长期、可持续的稳定增值。',
            feature: '高风险',
            standard: '中证800指数×80％＋中国债券总指数×20％',
            range: '主要投资于股票类资产，在股票行业配置方面，本基金优先投资于和经济增长最为密切的内需拉动型行业中的优势企业。对这些行业的投资占股票投资的比重不低于80%。',
            tactics: '股票投资部分以“内需拉动型” 行业的优势企业为主，以成长、价值及稳定收入为基础，在合适的价位买入具有高成长性的成长型股票，价值被市场低估的价值型股票，以及能提供稳定收入的收益型股票。债券投资部分着重本金安全性和流动性。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/260104/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengNeiXuZengZhangKaiFangShiZhengQuanTouZiJiJinHeTong',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/260104/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/260104/detail.html',
            protocol: 'JingShunChangChengNeiXuZengZhangKaiFangShiZhengQuanTouZiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        2: {
            name: '景顺长城内需增长贰号混合型证券投资基金',
            code: '260109',
            cate: '混合型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260109/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260109/detail.html\');">点击查看</a>',
            date: '2006年10月11日',
            risk: '4',
            rate: 'http://www.igwfmc.com/main/jjcp/product/260109/detail.html',
            share: '现金分红',
            intro: 'jingshunchangcheng.htm',
            target: '通过优先投资于内需拉动型行业中的优势企业，分享中国经济和行业的快速增长带来的最大收益，实现基金资产的长期、可持续的稳定增值。',
            feature: '高风险',
            standard: '中证800指数×80%＋中国债券总指数×20%',
            range: '主要投资于股票类资产，在股票行业配置方面，本基金优先投资于和经济增长最为密切的内需拉动型行业中的优势企业。对这些行业的投资占股票投资的比重不低于80%。',
            tactics: '股票投资部分以“内需拉动型” 行业的优势企业为主，以成长、价值及稳定收入为基础，在合适的价位买入具有高成长性的成长型股票，价值被市场低估的价值型股票，以及能提供稳定收入的收益型股票。债券投资部分着重本金安全性和流动性。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/260109/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengNeiXuZengZhangKaiFangShiZhengQuanTouZiJiJinHeTong2',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/260109/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/260109/detail.html',
            protocol: 'JingShunChangChengNeiXuZengZhangKaiFangShiZhengQuanTouZiJiJinTuoGuanXieYi2',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        5: {
            name: '景顺长城能源基建混合型证券投资基金',
            code: '260112',
            cate: '混合型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260112/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260112/detail.html\');">点击查看</a>',
            date: '2009年10月20日',
            risk: '3',
            rate: 'http://www.igwfmc.com/main/jjcp/product/260112/detail.html',
            share: '现金分红',
            intro: 'jingshunchangcheng.htm',
            target: '通过把握中国能源及基础设施建设需求带来的相关产业成长机会，实现长期资本增值。',
            feature: '高风险',
            standard: '沪深300指数×80%＋中证全债指数×20%',
            range: '本基金投资于具有良好流动性的金融工具，包括国内依法发行和上市交易的公司股票和债券以及经中国证监会批准的允许基金投资的其他金融工具。如法律法规或监管机构以后允许基金投资股票指数期货等其他品种，基金管理人在履行适当程序后，可以将其纳入投资范围。<br>本基金股票投资比例范围为基金资产的60-95%，持有现金或者到期日在一年以内的政府债券的比例不低于基金资产净值的5%。<br>本基金投资于与能源及基建业务相关的上市公司所发行股票的比例高于基金股票投资的80%。',
            tactics: '股票投资遵循“自下而上”与“自上而下”相结合的投资策略，寻找投资主题当中最具爆发力子行业中的龙头企业。债券投资采取利率预期策略、流动性策略和时机策略相结合的积极性投资方法，力求在控制各类风险的基础上为投资者获取稳定的收益。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/260112/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengNengYuanJiJianJiJinHeTong',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/260112/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/260112/detail.html',
            protocol: 'JingShunChangChengNengYuanJiJianGuPiaoXingZhengQuanTouZiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        4: {
            name: '景顺长城优选混合型证券投资基金',
            code: '260101',
            cate: '混合型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260101/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260101/detail.html\');">点击查看</a>',
            date: '2003年10月24日',
            risk: '4',
            rate: 'http://www.igwfmc.com/main/jjcp/product/260101/detail.html',
            share: '现金分红',
            intro: 'jingshunchangcheng.htm',
            target: '本基金采取“自下而上”结合“自上而下”的投资策略，以成长、价值及收益为基础，在合适的价位买入具有高成长性的成长型股票、价值被市场低估的价值型股票以及能提供稳定收益的收益型股票。',
            feature: '高风险',
            standard: '中证800指数×80%＋中国债券总指数×20%',
            range: '景顺长城优选股票基金投资于股票、国债、金融债、企业（公司）债、可转换债及中国证监会批准的其他投资品种，或保持现金。',
            tactics: '本基金采取“自下而上”结合“自上而下”的投资策略，以成长、价值及收益为基础，在合适的价位买入具有高成长性的成长型股票、价值被市场低估的价值型股票以及能提供稳定收益的收益型股票。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/260101/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengYouXuanGuPiaoJiJinHeTong',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/260101/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/260101/detail.html',
            protocol: 'JingShunChangChengJingXiLieKaiFangShiZhengQuanTouZiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        9: {
            name: '景顺长城货币市场证券投资基金A',
            code: '260102',
            cate: '货币型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260102/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260102/detail.html\');">点击查看</a>',
            date: '2003年10月24日',
            risk: '1',
            rate: 'http://www.igwfmc.com/main/jjcp/product/260102/detail.html',
            share: '红利再投资',
            intro: 'jingshunchangcheng.htm',
            target: '在保持本金的高流动性和安全性的前提下，获得高于基准的投资回报。',
            feature: '低风险',
            standard: '税后同期7天存款利率',
            range: '本基金投资于以下金融工具：<br>1、现金；<br>2、一年以内（含一年）的银行定期存款、大额存单；<br>3、剩余期限在三百九十七天以内（含三百九十七天）的债券；<br>4、期限在一年以内（含一年）的债券回购；<br>5、期限在一年以内（含一年）的中央银行票据；<br>6、中国证监会、中国人民银行认可的其他具有良好流动性的货币市场工具。',
            tactics: '本基金通过宏观经济、政策和市场资金供求的综合分析进行短期利率判断，对各投资品种从收益率、流动性、信用风险、平均剩余期限等方面进行综合价值比较，在保持基金资产高流动性的前提下构建组合。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/260102/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengHuoBiShiChangZhengQuanTouZiAJiJinHeTong',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/260102/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/260102/detail.html',
            protocol: 'JingShunChangChengHuoBiShiChangZhengQuanTouZiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        10: {
            name: '景顺长城货币市场证券投资基金B',
            code: '260202',
            cate: '货币型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260202/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/260202/detail.html\');">点击查看</a>',
            date: '2010年04月30日',
            risk: '1',
            rate: 'http://www.igwfmc.com/main/jjcp/product/260202/detail.html',
            share: '红利再投资',
            intro: 'jingshunchangcheng.htm',
            target: '在保持本金的高流动性和安全性的前提下，获得高于基准的投资回报。',
            feature: '低风险',
            standard: '税后同期7天存款利率',
            range: '本基金投资于以下金融工具：<br>1、现金；<br>2、一年以内（含一年）的银行定期存款、大额存单；<br>3、剩余期限在三百九十七天以内（含三百九十七天）的债券；<br>4、期限在一年以内（含一年）的债券回购；<br>5、期限在一年以内（含一年）的中央银行票据；<br>6、中国证监会、中国人民银行认可的其他具有良好流动性的货币市场工具。',
            tactics: '本基金通过宏观经济、政策和市场资金供求的综合分析进行短期利率判断，对各投资品种从收益率、流动性、信用风险、平均剩余期限等方面进行综合价值比较，在保持基金资产高流动性的前提下构建组合。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/260202/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengHuoBiShiChangZhengQuanTouZiBJiJinHeTong',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/260202/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/260202/detail.html',
            protocol: 'JingShunChangChengHuoBiShiChangZhengQuanTouZiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        2022: {
            name: '景顺长城资源垄断混合型证券投资基金（LOF）',
            code: '162607',
            cate: '混合型',
            comp: '景顺长城基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/162607/detail.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.igwfmc.com/main/jjcp/product/162607/detail.html\');">点击查看</a>',
            date: '2006年01月26日',
            risk: '3',
            rate: 'http://www.igwfmc.com/main/jjcp/product/162607/detail.html',
            share: '现金分红',
            intro: 'jingshunchangcheng.htm',
            target: '本基金以长期看好中国经济增长和资本市场发展为立足点，重点投资于具有自然资源优势以及垄断优势的优秀上市公司股票，以获取基金资产的长期稳定增值。',
            feature: '高风险',
            standard: '沪深300指数*80%+中国债券总指数*20%',
            range: '本基金投资于具有良好流动性的金融工具，包括国内依法发行和上市交易的公司股票和债券以及经中国证监会批准的允许基金投资的其他金融工具。',
            tactics: '本基金以长期看好中国经济增长和资本市场发展为立足点，重点投资于具有自然资源优势以及垄断优势的优秀上市公司股票，以获取基金资产的长期稳定增值。',
            notice: 'http://www.igwfmc.com/main/jjcp/product/162607/detail.html',
            record: 'dailylmfnav',
            agreement: 'JingShunChangChengZiYuanLongDuanJiJinHeTong',
            investmentcontract: 'http://www.igwfmc.com/main/jjcp/product/162607/detail.html',
            instruction: 'http://www.igwfmc.com/main/jjcp/product/162607/detail.html',
            protocol: 'JingShunChangChengZiYuanLongDuanJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        7: {
            name: '泰达宏利价值优化型稳定类行业混合型证券投资基金',
            code: '162203',
            cate: '混合型',
            comp: '泰达宏利基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.mfcteda.com/Channel/982200\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.mfcteda.com/Channel/982200\');">点击查看</a>',
            date: '2003年04月25日',
            risk: '3',
            rate: 'http://www.mfcteda.com/Channel/982200',
            share: '现金分红',
            intro: 'taidahongli.htm',
            target: '在有效控制投资组合风险下，为投资者提供长期稳定的投资回报。',
            feature: '较高风险',
            standard: '65%富时中国A600稳定行业指数+35%上证国债指数',
            range: '限于具有良好流动性的金融工具，包括投资于国内依法公开发行、上市的股票和债券以及中国证监会允许基金投资的其它金融工具。',
            tactics: '动态资产配置。每只行业类基金根据市场状况，随时调整每只基金在股票、债券、现金上的投资比重。',
            notice: 'http://www.mfcteda.com/Channel/981644',
            record: 'dailylmfnav',
            agreement: 'TaiDaHongLiWenDingGuPiaoJiJinHeTong',
            investmentcontract: 'http://www.mfcteda.com/Channel/982200',
            instruction: 'http://www.mfcteda.com/Channel/982200',
            protocol: 'TaiDaHongLiWenDingGuPiaoTouZiXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        6: {
            name: '泰达宏利行业精选混合型证券投资基金',
            code: '162204',
            cate: '混合型',
            comp: '泰达宏利基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.mfcteda.com/Channel/961977\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.mfcteda.com/Channel/961977\');">点击查看</a>',
            date: '2004年07月09日',
            risk: '3',
            rate: 'http://www.mfcteda.com/Channel/961977',
            share: '现金分红',
            intro: 'taidahongli.htm',
            target: '追求资本的长期持续增值，在有效的风险控制下为投资者寻求高于业绩比较基准的投资回报。',
            feature: '较高风险',
            standard: '70%×富时中国A600指数收益率+30%×中债国债总指数（财富）',
            range: '主要投资于具有成长潜力且价格被低估的精选绩优企业股票及其他具有良好流动性的金融工具。基金投资于股票的比例为基金资产净值的60%－95%；基金投资于债券的比例为基金资产净值的0－35%；现金为5%－30%。',
            tactics: '相信资产的增值主要来源于资产配置、行业配置和个股的选择。在力求强调"纪律投资"的同时，依靠外资支持，全面地引进国际先进的投资管理流程——根据市场环境，通过资产配置"自上而下"地控制和调整仓位；根据国际趋势和国内行业研究成果，通过行业配置准确把握行业轮动；通过专业人员的深入调研和分析，"自下而上"地精选个股；最后通过严谨科学的风险控制工具控制和降低投资风险。',
            notice: 'http://www.mfcteda.com/Channel/961424',
            record: 'dailylmfnav',
            agreement: 'TaiDaHongLiJingXuanGuPiaoJiJinHeTong',
            investmentcontract: 'http://www.mfcteda.com/Channel/961977',
            instruction: 'http://www.mfcteda.com/Channel/961977',
            protocol: 'TaiDaHongLiJingXuanGuPiaoTouZiXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        1013: {
            name: '上投摩根货币市场基金',
            code: '370010',
            cate: '货币型',
            comp: '上投摩根基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/370010/\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/370010/\');">点击查看</a>',
            date: '2005年04月13日',
            risk: '1',
            rate: 'http://www.51fund.com/fund/370010/fee/#go',
            share: '红利转再投',
            intro: 'shangtoumogen.htm',
            target: '通过合理的资产选择，在有效控制风险和保持较高流动性的前提下，为投资者提供资金的流动性储备，进一步优化现金管理，并力求获得高于业绩比较基准的稳定回报。',
            feature: '投资组合的平均剩余期限控制在120天以内；属于风险低、流动性强、预期收益率稳健的基金产品。',
            standard: '同期七天通知存款利率（税后）',
            range: '现金；一年以内（含一年）的银行定期存款、大额存单；剩余期限在三百九十七天以内 （含三百九十七天）的债券；期限在一年以内（含一年）的债券回购；期限在一年以内 （含一年）的中央银行票据；中国证监会、中国人民银行认可的其他具有良好流动性的货币市场工具。',
            tactics: '本基金投资管理将充分运用收益率策略与估值策略相结合的方法，对各类可投资资产进行合理的配置和选择。投资策略首先审慎考虑各类资产的收益性，流动性及风险性特征，在风险与收益的配比中，力求将各类风险降到最低，并在控制投资组合良好流动性的基础上为投资者获取稳定的收益。',
            notice: 'http://www.51fund.com/fund/370010/announce/#go',
            record: 'dailylmfnav',
            agreement: 'ShangTouMoGenHuoBiShiChangJiJinHeTong',
            investmentcontract: 'https://www.cifm.com/fund/370010/',
            instruction: 'https://www.cifm.com/fund/370010/',
            protocol: 'ShangTouMoGenHuoBiShiChangTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        1020: {
            name: '上投摩根双核平衡混合型证券投资基金',
            code: '373020',
            cate: '混合型',
            comp: '上投摩根基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/373020\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/373020\');">点击查看</a>',
            date: '2008年05月21日',
            risk: '3',
            rate: 'http://www.51fund.com/fund/373020/fee/#go',
            share: '现金红利',
            intro: 'shangtoumogen.htm',
            target: '本基金深化价值投资理念，精选具备较高估值优势的上市公司股票与优质债券等，持续优化投资风险与收益的动态匹配，通过积极主动的组合管理，追求基金资产的长期稳定增值。',
            feature: '本基金是混合型基金，在证券投资基金中属于中高风险品种，其预期风险收益水平低于股票型基金，高于债券基金与货币市场基金。',
            standard: '沪深300指数收益率×50%＋上证国债指数收益率×50％',
            range: '本基金的投资范围为具有良好流动性的金融工具，包括国内依法发行上市的股票、债券及法律、法规或中国证监会允许基金投资的其他金融工具。 在正常市场情况下，本基金投资组合中股票投资比例为基金资产的40％－70％，债券及其它短期金融工具为25-55％，并保持不低于基金资产净值5％的现金或者到期日在一年以内的政府债券。对于中国证监会允许投资的创新金融产品，将依据有关法律法规进行投资管理。本基金投资重点是具备较高估值优势的上市公司股票等，80％以上的股票基金资产属于上述投资方向所确定的内容。 如果法律法规对上述比例要求有变更的，本基金投资范围将及时做出相应调整，以调整变更后的比例为准。',
            tactics: '本基金将运用安全边际策略有效挖掘价值低估的股票类投资品种。在控制宏观经济趋势、产业发展周期等宏观经济环境变量基础上，考察上市公司的商业模式、管理能力、财务状况等影响企业持续经营的因素，然后综合运用量化价值模型来衡量股票价格是高估还是低估。本基金的债券投资策略是建立在对债券核心内在价值的认识上。我们将采用更为有效的债券估值模型，同时综合考虑宏观经济运行状况、金融市场环境及利率走势，采取至上而下和至下而上结合的投资策略积极配置资产。在控制利率风险、信用风险以及流动性风险的基础上，通过组合投资为投资者创造长期回报。',
            notice: 'http://www.51fund.com/fund/373020/announce/#go',
            record: 'dailylmfnav',
            agreement: 'ShangTouMoGenShuangHePingHengJiJinHeTong',
            investmentcontract: 'https://www.cifm.com/fund/373020',
            instruction: 'https://www.cifm.com/fund/373020',
            protocol: 'ShangTouMoGenShuangHePingHengTuoGuanXiYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        1021: {
            name: '上投摩根分红添利债券型证券投资基金A',
            code: '370021',
            cate: '债券型',
            comp: '上投摩根基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/370021\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/370021\');">点击查看</a>',
            date: '2012年06月25日',
            risk: '2',
            rate: 'http://www.51fund.com/fund/370021/fee/#go',
            share: '现金红利',
            intro: 'shangtoumogen.htm',
            target: '在有效控制风险和保持资产流动性的前提下，通过积极主动的投资管理，力争为投资者创造稳定的当期收益和长期回报。',
            feature: '本基金为债券型基金，属于证券投资基金中的较低风险品种，预期风险和预期收益高于货币市场基金，低于混合型基金和股票型基金。',
            standard: '中证综合债券指数',
            range: '本基金的投资组合比例为：固定收益类资产的投资比例不低于基金资产的80%，股票、权证等权益类资产的投资比例不超过基金资产的20%，保持不低于基金资产净值5%的现金或到期日在一年以内的政府债券。',
            tactics: '本基金采取自上而下的方法确定组合久期，结合自下而上的个券选择方法构建债券投资组合。通过对固定收益资产的投资，获取稳定的投资收益；在此基础上，适当参与新股发行申购及增发新股申购，在严格控制资产运作风险的基础上，实现基金资产的长期增值。',
            notice: 'http://www.51fund.com/fund/370021/announce/#go',
            record: 'dailylmfnav',
            agreement: 'ShangTouMoGenFenHongTianLiJiJinHeTong',
            investmentcontract: 'https://www.cifm.com/fund/370021',
            instruction: 'https://www.cifm.com/fund/370021',
            protocol: 'ShangTouMoGenFenHongTianLiTuoGuanXiYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        3021: {
            name: '上投摩根新兴动力混合型证券投资基金',
            code: '377240',
            cate: '混合型',
            comp: '上投摩根基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/377240\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/377240\');">点击查看</a>',
            date: '2011年07月31日',
            risk: '4',
            rate: 'http://www.51fund.com/fund/377240/fee/#go',
            share: '现金分红',
            intro: 'shangtoumogen.htm',
            target: '本基金在把握经济结构调整和产业升级的发展趋势基础上，充分挖掘新兴产业发展中的投资机会，重点关注新兴产业中的优质上市公司，并兼顾传统产业中具备新成长动力的上市公司进行投资，在有效控制风险的前提下，追求基金资产的稳定增值。',
            feature: '本基金属于混合型基金产品，预期风险和收益水平低于股票型基金，高于债券型基金和货币市场基金，属于风险水平较高的基金产品。',
            standard: '沪深300指数收益率×80%+上证国债指数收益率×20%',
            range: '股票等权益类资产占基金资产的60%-95%，债券等固定收益类资产占基金资产的0-40%，权证投资占基金资产净值的0-3%，现金或到期日在一年期以内的政府债券不低于基金资产净值的5%。本基金将不低于80%的股票资产投资于新兴产业中的优质上市公司和传统产业中具备新成长动力的上市公司股票。如法律法规或监管机构以后允许基金投资的其他品种，基金管理人在履行适当程序后，可以将其纳入投资范围。',
            tactics: '本基金一方面将从新兴产业出发，深入挖掘新兴产业发展过程中带来的投资机会，另一方面将关注传统产业中成长公司的投资。',
            notice: 'http://www.51fund.com/fund/377240/announce/#go',
            record: 'dailylmfnav',
            agreement: 'ShangTouMoGenXinXingDongliJiJinHeTong',
            investmentcontract: 'https://www.cifm.com/fund/377240',
            instruction: 'https://www.cifm.com/fund/377240',
            protocol: 'ShangTouMoGenXinXingDongliTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        3022: {
            name: '上投摩根行业轮动混合型证券投资基金',
            code: '377530',
            cate: '混合型',
            comp: '上投摩根基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/377530\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/377530\');">点击查看</a>',
            date: '2010年01月28日',
            risk: '4',
            rate: 'http://www.51fund.com/fund/377530/fee/#go',
            share: '现金分红',
            intro: 'shangtoumogen.htm',
            target: '本基金通过把握资产轮动、产业策略与经济周期相联系的规律，挖掘经济周期波动中强势行业中具有核心竞争优势的上市公司，力求在景气的多空变化中把握行业轮动挖掘投资机会。',
            feature: '本基金是主动管理的混合型证券投资基金，属于证券投资基金的较高风险品种，预期风险收益水平低于股票型基金，高于债券型基金和货币市场基金。',
            standard: '沪深300指数收益率×80%+上证国债指数收益率×20%',
            range: '股票：60%－95%，债券及其它短期金融工具：5%－40%，并保持不低于基金资产净值5％的现金或者到期日在一年以内的政府债券。本基金将不低于80%的股票资产投资于强势行业中具有核心竞争优势的上市公司股票。',
            tactics: '本基金通过把握经济周期变化，依据对宏观经济、产业政策、行业景气度及市场波动等因素的综合判断，采取自上而下的资产配置策略、行业配置策略与自下而上的个股选择策略相结合，精选强势行业中具有核心竞争优势的个股，力求无论在多空市场环境下均能获取稳健的超额回报。',
            notice: 'http://www.51fund.com/fund/377530/announce/#go',
            record: 'dailylmfnav',
            agreement: 'ShangTouMoGenHangYeLunDongJiJinHeTong',
            investmentcontract: 'https://www.cifm.com/fund/377530',
            instruction: 'https://www.cifm.com/fund/377530',
            protocol: 'ShangTouMoGenHangYeLunDongTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        1014: {
            name: '海富通收益增长证券投资基金',
            code: '519003',
            cate: '混合型',
            comp: '海富通基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/hunhe/519003/index.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/hunhe/519003/index.html\');">点击查看</a>',
            date: '2004年03月12日',
            risk: '4',
            rate: 'http://www.hftfund.com/products/hunhe/519003/index.html',
            share: '现金分红',
            intro: 'haifutong.htm',
            target: '建立随时间推移非负增长的收益增长线，运用优化组合保险机制实现风险预算管理，力争基金单位资产净值高于收益增长线水平。在此基础上，通过精选证券和适度主动地把握市场时机，将中国经济的高速成长转化为基金资产的长期稳定增值。',
            feature: '属于证券投资基金中风险较低的产品，追求在风险预算目标下基金资产增值的最大化。',
            standard: '本基金股票投资部分的业绩比较基准是MSCI China A指数，债券投资部分的业绩比较基准是上证国债指数。基金业绩比较基准参照MSCI China A指数×40%+上证国债指数×60%。<br>* MSCI China A指数：摩根斯坦利资本国际--中国A股指数。',
            range: '本基金的投资范围限于具有良好流动性的金融工具，包括国内依法发行上市的股票、债券及法律、法规或中国证监会允许基金投资的其他金融工具。在正常市场情况下，本基金投资组合的基本范围：股票资产0－80％，债券资产20－100％。可转换债券具有与本基金相似的风险收益特征，在条件成熟时将成为本基金的重点投资对象。',
            tactics: '整体投资策略分为三个层次：第一层次，以优化投资组合保险策略为核心，并结合把握市场时机，确定和调整基金资产在债券和股票间的配置比例，实现风险预算管理、降低系统性风险，保证基金投资目标的实现；第二层次，采用自上而下的策略，以久期管理为核心，从整体资产配置、类属资产配置和个券选择三个层次进行积极主动的债券投资管理，保证基金单位资产净值超越收益增长线；第三层次，从定价指标、盈利预测指标和流动性指标三个方面，积极主动精选个股和构建分散化的股票组合，控制非系统性风险，充分获取股市上涨收益。',
            notice: 'http://www.hftfund.com/products/hunhe/519003/index.html',
            record: 'dailylmfnav',
            agreement: 'HaiFuTongShouYiZengZhangJiJinHeTong',
            investmentcontract: 'http://www.hftfund.com/products/hunhe/519003/index.html',
            instruction: 'http://www.hftfund.com/products/hunhe/519003/index.html',
            protocol: 'HaiFuTongShouYiZengZhangTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        1015: {
            name: '海富通股票混合型证券投资基金',
            code: '519005',
            cate: '混合型',
            comp: '海富通基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/hunhe/519005/index.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/hunhe/519005/index.html\');">点击查看</a>',
            date: '2005年07月29日',
            risk: '4',
            rate: 'http://www.hftfund.com/products/hunhe/519005/index.html',
            share: '现金分红',
            intro: 'haifutong.htm',
            target: '精选景气行业和积极主动精选股票投资相结合，分享中国经济高速成长的成果，谋求基金资产的长期最大化增值。',
            feature: '本基金属于证券投资基金中较高风险，较高收益的混合型基金产品。',
            standard: '本基金股票投资部分的业绩比较基准是MSCI China A指数，债券投资部分的业绩比较基准是上证国债指数。<br>基金业绩比较基准　＝MSCI China A指数×80％＋上证国债指数×20％。<br>* MSCI China A指数：摩根斯坦利资本国际--中国A股指数。',
            range: '本基金投资范围限于具有良好流动性的金融工具，包括国内依法发行上市的股票、债券及法律、法规或中国证监会允许基金投资的其他金融工具。在正常市场情况下，本基金投资组合的基本范围：股票资产70％-95%，权证投资0-3%，一年期以内的政府债券和现金的比例不低于5％。',
            tactics: '本基金采用双层次的投资策略：第一层次主要通过对股票市场的系统性风险进行分析，确定股票和现金资产的配置比例；第二层次主要是通过对行业景气循环和个股的研究，精选适合本投资组合风险收益特征的股票。',
            notice: 'http://www.hftfund.com/products/hunhe/519005/index.html',
            record: 'dailylmfnav',
            agreement: 'HaiFuTongGuPiaoZhengQuanJiJinHeTong',
            investmentcontract: 'http://www.hftfund.com/products/hunhe/519005/index.html',
            instruction: 'http://www.hftfund.com/products/hunhe/519005/index.html',
            protocol: 'HaiFuTongGuPiaoZhengQuanTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        1016: {
            name: '海富通精选证券投资基金',
            code: '519011',
            cate: '混合型',
            comp: '海富通基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/hunhe/519011/index.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/hunhe/519011/index.html\');">点击查看</a>',
            date: '2003年08月22日',
            risk: '4',
            rate: 'http://www.hftfund.com/products/hunhe/519011/index.html',
            share: '现金分红',
            intro: 'haifutong.htm',
            target: '采取积极主动精选证券和适度主动进行资产配置的投资策略，实施全程风险管理，在保证资产良好流动性的前提下，在风险限度内实现基金资产的长期最大化增值。',
            feature: '海富通精选证券投资基金属于中度风险的平衡型基金。管理人将力争通过适度主动的资产配置和积极主动的精选证券，识别和控制风险，实现风险限度内的超额回报。',
            standard: '本基金股票投资部分的业绩比较基准是MSCI China A指数，债券投资部分的业绩比较基准是上证国债指数。基金业绩比较基准＝MSCI China A指数×65％＋上证国债指数×35％<br>* MSCI China A指数：摩根斯坦利资本国际--中国A股指数。',
            range: '限于具有良好流动性的金融工具，包括国内依法发行上市的股票、债券及法律、法规或中国证监会允许基金投资的其他金融工具。',
            tactics: '本基金的投资策略分两个层次：第一层次为适度主动的资产配置，以控制或规避市场系统性风险；第二层次为积极主动的精选证券，以分散或规避个券风险。积极主动精选证券是本基金投资策略的重点。',
            notice: 'http://www.hftfund.com/products/hunhe/519011/index.html',
            record: 'dailylmfnav',
            agreement: 'HaiFuTongJingXuanZhengQuanJiJinHeTong',
            investmentcontract: 'http://www.hftfund.com/products/hunhe/519011/index.html',
            instruction: 'http://www.hftfund.com/products/hunhe/519011/index.html',
            protocol: 'HaiFuTongJingXuanZhengQuanTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        1017: {
            name: '海富通风格优势混合型证券投资基金',
            code: '519013',
            cate: '混合型',
            comp: '海富通基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/hunhe/519013/index.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/hunhe/519013/index.html\');">点击查看</a>',
            date: '2006年10月19日',
            risk: '4',
            rate: 'http://www.hftfund.com/products/hunhe/519013/index.html',
            share: '现金分红',
            intro: 'haifutong.htm',
            target: '在适度控制风险并保持资产良好流动性的前提下，通过积极选择不同风格优势的股票，力争为投资者提供长期稳定的超额回报。',
            feature: '本基金是混合型基金，属于较高风险、较高收益的投资品种。',
            standard: 'MSCI China A指数75%＋上证国债指数25%',
            range: '本基金的投资范围限于具有良好流动性的金融工具，包括国内依法公开发行上市的股票、国债、金融债、企业债、回购、央行票据、可转换债券、权证以及经中国证监会批准允许基金投资的其它金融工具。如法律法规或监管机构以后允许基金投资的其他产品，基金管理人在履行适当的程序后，可以将其纳入投资范围。在通常市场情况下，基金投资组合中股票资产占基金资产的60%～95%，权证投资0%～3%，现金、债券、货币市场工具以及中国证监会允许基金投资的其他金融工具占基金资产的5%～40%，其中，基金保留的现金或者投资于一年期以内的政府债券的比例合计不低于基金资产净值的5%。',
            tactics: '本基金将在适度的大类资产配置的基础上，运用“风格优选，积极轮换，精选个股”策略，把握不同风格优势策略在不同阶段的变动趋势和投资机会，并在策略内自下而上精选个股，实现基金资产的超额收益。本基金的投资策略主要包括资产配置策略、风格轮换策略和精选证券策略。',
            notice: 'http://www.hftfund.com/products/hunhe/519013/index.html',
            record: 'dailylmfnav',
            agreement: 'HaiFuTongFengGeYouShiJiJinHeTong',
            investmentcontract: 'http://www.hftfund.com/products/hunhe/519013/index.html',
            instruction: 'http://www.hftfund.com/products/hunhe/519013/index.html',
            protocol: 'HaiFuTongFengGeYouShiTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        1018: {
            name: '海富通货币市场证券投资基金A',
            code: '519505',
            cate: '货币型',
            comp: '海富通基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/huobi/519505/index.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/huobi/519505/index.html\');">点击查看</a>',
            date: '2005年01月04日',
            risk: '2',
            rate: 'http://www.hftfund.com/products/huobi/519505/index.html',
            share: '红利再投资',
            intro: 'haifutong.htm',
            target: '在力争本金安全和资产充分流动性的前提下，追求超过业绩比较基准的收益。',
            feature: '本基金是具有较低风险、流动性强的证券投资基金品种。',
            standard: '税后一年期银行定期存款利率。',
            range: '现金；期限1年以内（含1年）的银行存款、债券回购、中央银行票据、同业存单；剩余期限在397天以内（含397天）的债券；中国证监会、中国人民银行认可的其他具有良好流动性的货币市场工具。',
            tactics: '根据宏观经济指标（主要包括：利率水平、通货膨胀率、GDP增长率、货币供应量、就业率水平、国际市场利率水平、汇率），决定债券组合的剩余期限（长/中/短）和比例分布。根据各类资产的流动性特征（主要包括：平均日交易量、交易场所、机构投资者持有情况、回购抵押数量、分拆转换进程），决定组合中各类资产的投资比例。根据债券的信用等级及担保状况，决定组合的风险级别。',
            notice: 'http://www.hftfund.com/products/huobi/519505/index.html',
            record: 'dailylmfnav',
            agreement: 'HaiFuTongHuoBiShiChaneJiJinHeTong',
            investmentcontract: 'http://www.hftfund.com/products/huobi/519505/index.html',
            instruction: 'http://www.hftfund.com/products/huobi/519505/index.htmlu',
            protocol: 'HaiFuTongHuoBiShiChaneTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        1019: {
            name: '海富通货币市场证券投资基金B',
            code: '519506',
            cate: '货币型',
            comp: '海富通基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/huobi/519506/index.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.hftfund.com/products/huobi/519506/index.html\');">点击查看</a>',
            date: '2005年01月04日',
            risk: '2',
            rate: 'http://www.hftfund.com/products/huobi/519506/index.html',
            share: '红利再投资',
            intro: 'haifutong.htm',
            target: '在力争本金安全和资产充分流动性的前提下，追求超过业绩比较基准的收益。',
            feature: '本基金是具有较低风险、流动性强的证券投资基金品种。',
            standard: '税后一年期银行定期存款利率。',
            range: '现金；期限1年以内（含1年）的银行存款、债券回购、中央银行票据、同业存单；剩余期限在397天以内（含397天）的债券；中国证监会、中国人民银行认可的其他具有良好流动性的货币市场工具。',
            tactics: '根据宏观经济指标（主要包括：利率水平、通货膨胀率、GDP增长率、货币供应量、就业率水平、国际市场利率水平、汇率），决定债券组合的剩余期限（长/中/短）和比例分布。根据各类资产的流动性特征（主要包括：平均日交易量、交易场所、机构投资者持有情况、回购抵押数量、分拆转换进程），决定组合中各类资产的投资比例。根据债券的信用等级及担保状况，决定组合的风险级别。',
            notice: 'http://www.hftfund.com/products/huobi/519506/index.html',
            record: 'dailylmfnav',
            agreement: 'HaiFuTongHuoBiShiChaneJiJinHeTong',
            investmentcontract: 'http://www.hftfund.com/products/huobi/519506/index.html',
            instruction: 'http://www.hftfund.com/products/huobi/519506/index.html',
            protocol: 'HaiFuTongHuoBiShiChaneTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        4023: {
            name: '博时现金收益证券投资基金A',
            code: '050003',
            cate: '货币型',
            comp: '博时基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.bosera.com/fund/050003.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.bosera.com/fund/050003.html\');">点击查看</a>',
            date: '2004年01月16日',
            risk: '2',
            rate: 'http://www.bosera.com/fund/050003.html',
            share: '红利再投',
            intro: 'boshi.htm',
            target: '在保持低风险和高流动性的前提下获得高于投资基准的回报',
            feature: '低风险',
            standard: '活期存款利率（税后）',
            range: '到期期限在一年以内的国债、金融债、央行票据、AAA级企业债等短期债券；债券回购；同业存款；证监会、人民银行等部门批准基金投资的商业票据及其他流动性良好的短期金融工具',
            tactics: '本基金根据短期利率的变动和市场格局的变化，积极主动地在债券资产和回购资产之间进行动态地资产配置。通过对中长期回购利率波动规律的把握对回购资产进行时间方向上的动态配置策略。同时根据回购利差进行回购品种的配置比例调整。',
            notice: 'http://www.bosera.com/column/index.do?classid=0002000200030005&fundCode=050003',
            record: 'dailylmfnav',
            agreement: 'BoShiXianJinShouYiJiJinHeTong',
            investmentcontract: 'http://www.bosera.com/column/index.do?classid=0002000200030004&fundCode=050003',
            instruction: 'http://www.bosera.com/fund/050003.html',
            protocol: 'BoShiXianJinShouYiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br />风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        4022: {
            name: '博时主题行业混合型证券投资基金(LOF)',
            code: '160505',
            cate: '混合型',
            comp: '博时基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.bosera.com/fund/160505.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.bosera.com/fund/160505.html\');">点击查看</a>',
            date: '2005年01月06日',
            risk: '3',
            rate: 'http://www.bosera.com/fund/160505.html',
            share: '现金分红',
            intro: 'boshi.htm',
            target: '分享中国城市化、工业化及消费升级进程中经济与资本市场的高速成长，谋求基金资产的长期稳定增长',
            feature: '中高风险',
            standard: '80%×富时中国A600指数+20%×富时中国国债指数',
            range: '本基金的投资范围为具有良好流动性的金融工具，包括国内依法发售上市的股票、债券及法律法规或中国证监会允许基金投资的其他金融工具。本基金主要投资于股票，股票资产占基金净值的比例范围为60%-95%。基金保留的现金以及投资于到期在1年期以内的政府债券等短期金融工具的资产比例合计不低于5%',
            tactics: '本基金的业绩基准为富时中国A600指数，因此，本基金的股票资产在消费品、基础设施及原材料等三大行业的配置比例将以富时中国A600指数中消费品、基础设施及原材料等三大行业的权重作为配置基准。在基金的实际投资管理中，本基金将根据行业投资价值评估结果结合个股精选结果，动态调整基金资产在消费品、基础设施及原材料等三大行业间的投资比例。',
            notice: 'http://www.bosera.com/column/index.do?classid=0002000200030005&fundCode=160505',
            record: 'dailylmfnav',
            agreement: 'BoShiZhuTiHangYeJiJinHeTong',
            investmentcontract: 'http://www.bosera.com/column/index.do?classid=0002000200030004&fundCode=160505',
            instruction: 'http://www.bosera.com/fund/160505.html',
            protocol: 'BoShiZhuTiHangYeJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br />风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br /> **应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        4021: {
            name: '博时平衡配置混合型证券投资基金',
            code: '050007',
            cate: '混合型',
            comp: '博时基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.bosera.com/fund/050007.html\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.bosera.com/fund/050007.html\');">点击查看</a>',
            date: '2006年05月31日',
            risk: '4',
            rate: 'http://www.bosera.com/fund/050007.html',
            share: '现金分红',
            intro: 'boshi.htm',
            target: '本基金力争在股票、固定收益证券和现金等大类资产的适度平衡配置与稳健投资下，获取长期持续稳定的合理回报',
            feature: '中风险',
            standard: '45%×富时中国A600指数+50%×中国债券总指数+5%×同业存款利息率',
            range: '本基金主要投资于国内依法公开发行上市的股票、权证和国债、政策性金融债、企业债、次级债、短期融资券、可转换债券、债券回购、中央银行票据、银行存款，以及法律、法规或中国证监会允许基金投资的其他金融工具。本基金投资组合中股票投资比例为基金资产净值的30%-60%，股权分置改革中产生的权证的投资比例不得超过基金资产净值的3%并计入股票投资比例，固定收益类证券（含可转换债券及可分离可转换债券）投资比例为基金资产净值的0%-65%，现金以及到期日在一年以内的政府债券投资比例合计不低于基金资产净值的5%',
            tactics: '本基金遵循经济周期性波动规律，通过定性与定量分析，动态把握不同资产类在不同时期的投资价值、投资时机以及其风险收益特征的相对变化，追求股票、固定收益证券和现金等大类资产的适度平衡配置。在严格控制投资风险的前提下，追求基金资产的长期持续稳定增长',
            notice: 'http://www.bosera.com/column/index.do?classid=0002000200030005&fundCode=050007',
            record: 'dailylmfnav',
            agreement: 'BoShiPingHengPeiZhiJiJinHeTong',
            investmentcontract: 'http://www.bosera.com/column/index.do?classid=0002000200030004&fundCode=050007',
            instruction: 'http://www.bosera.com/fund/050007.html',
            protocol: 'BoShiPingHengPeiZhiJiJinTuoGuanXieYi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br />风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。'
        },
        4024: {
            name: '华夏兴华混合型证券投资基金',
            code: '519908',
            cate: '混合型',
            comp: '华夏基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.chinaamc.com/fund/519908/index.shtml\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.chinaamc.com/fund/519908/index.shtml\');">点击查看</a>',
            date: '2013年04月12日',
            risk: '4',
            rate: 'http://www.chinaamc.com/fund/519908/index.shtml',
            share: '现金分红',
            intro: 'huaxiaxinghuahunhe.htm',
            target: '密切跟踪经济动向，挖掘中国经济发展过程中所蕴含的机会，更好地分享中国经济较快成长的发展成果，力争实现基金资产的长期、持续增值。',
            feature: '本基金为混合基金，风险与收益高于债券基金与货币市场基金，低于股票基金，属于较高风险、较高收益的品种。',
            standard: '沪深 300 指数×70%＋上证国债指数×30%',
            range: '本基金的投资范围为具有良好流动性的金融工具，包括国内依法发行的股票（包括创业板、中小板股票）、债券（含中小企业私募债券）、货币市场工具、权证、资产支持证券、股指期货以及法律法规或中国证监会允许基金投资的其他金融工具。如法律法规或监管机构以后允许基金投资其他品种（如国债期货等金融衍生产品），基金管理人在履行适当程序后，可以将其纳入投资范围。本基金股票投资占基金资产的比例范围为 40%～95%，资产支持证券投资占基金资产净值的比例范围为 0～20%，权证投资占基金资产净值的比例范围为 0～3%。',
            tactics: '1、资产配置策略<br>本基金通过对宏观经济环境、政策形势、证券市场走势的综合分析，主动判断市场时机，进行积极的资产配置，合理确定基金在股票、债券等各类资产类别上的投资比例，并随着各类资产风险收益特征的相对变化，适时进行动态调整。<br>2、股票投资策略<br>本基金股票投资将重点关注具有可持续增长潜力的优势个股。在具体的股票选择上将采取定性分析与定量分析相结合的方法，充分挖掘股票价格与价值之间的差异，主动寻找其中蕴藏的投资机会。<br>（1）定性分析<br>a、行业地位：主要分析企业在行业中的竞争地位。运用波特“五力模型”，通过考察行业中新进入者的威胁、供应商的议价能力、购买商的议价能力、替代产品的威胁、同业竞争者的竞争强度这五种竞争驱动力，分析企业所在行业是否具有成长性；企业在行业中是否华夏兴华混合型证券投资基金招募说明书（更新）59占有一定竞争地位、是否有进一步发展的空间等。<br>b、经营能力：主要分析企业的创新能力和核心竞争力。企业是否富有创新精神及较强的研发能力；企业在资源、技术、品牌、效率、市场等方面是否具有竞争对手在较长的时间内难以模仿的独特优势等。<br>c、发展战略：主要分析企业的经营策略和战略规划。企业经营是否稳健，是否具有明确、合理的战略发展规划以及清晰、有效的经营策略；企业的战略执行力如何等。<br>d、公司治理：主要分析公司治理结构和管理能力。公司治理结构是否规范；管理团队是否稳定，是否具有丰富经验和具有进取精神；内部控制制度是否完善；是否具有良好的企业文化等。<br>（2）定量分析<br>定量分析主要采用多因子分析模型。具体如下：<br>a、估值因子：公司股票估值是否合理，主要指标包括市盈率、市净率等。<br>b、成长因子：公司的成长性是否良好，主要指标包括营业利润增长率等。<br>c、盈利因子：公司是否具有较强的盈利能力，主要指标包括 ROE 等。<br>d、市场因子：公司股票的市场价格走势及交易情况，主要指标包括换手率等。<br>（3）适时调整<br>在定性分析和定量分析的基础上确定优势个股,并结合组合风险特征分析、资产配置策略的变化等进行适当调整。<br>3、债券投资策略<br>结合对未来市场利率预期运用久期调整策略、收益率曲线配置策略、债券类属配置策略、利差轮动策略等多种积极管理策略，通过严谨的研究发现价值被低估的债券和市场投资机会，构建收益稳定、流动性良好的债券组合。<br>4、中小企业私募债券投资策略<br>在严格控制风险的前提下，通过严谨的研究，综合考虑中小企业私募债券的安全性、收益性和流动性等特征，并与其他投资品种进行对比后，选择具有相对优势的类属和个券进行投资。同时，通过期限和品种的分散投资降低基金投资中小企业私募债券的信用风险、利率风险和流动性风险。<br>5、权证投资策略<br>本基金将在严格控制风险的前提下，主动进行权证投资。基金权证投资将以价值分析为基础，在采用数量化模型分析其合理定价的基础上，把握市场的短期波动，进行积极操作，华夏兴华混合型证券投资基金招募说明书（更新）60追求在风险可控的前提下实现稳健的超额收益。<br>6、股指期货投资策略<br>本基金将在风险可控的前提下，本着谨慎原则，适度参与股指期货投资。通过对现货市场和期货市场运行趋势的研究，结合基金股票组合的实际情况及对股指期货的估值水平、基差水平、流动性等因素的分析，选择合适的期货合约构建相应的头寸，以调整投资组合的风险暴露，降低系统性风险。基金还将利用股指期货作为组合流动性管理工具，降低现货市场流动性不足导致的冲击成本过高的风险，提高基金的建仓或变现效率。<br>未来，根据市场情况，基金可相应调整和更新相关投资策略，并在招募说明书更新中公告。',
            notice: 'http://www.chinaamc.com/fund/519908/index.shtml',
            record: 'dailylmfnav',
            agreement: 'HuaXiaXingHuaHunHeHetong',
            investmentcontract: 'http://www.chinaamc.com/fund/519908/jijingonggao.shtml',
            instruction: 'http://www.chinaamc.com/fund/519908/index.shtml',
            protocol: 'HuaXiaXingHuaHunHeTuoguanxieyi',
            remark: '*以上信息更新至2018年1月，仅供参考；各基金产品及基金公司信息由基金公司提供，请以基金公司公布之信息为准。<br>风险评级为花旗银行（中国）有限公司内部核定，1至6代表产品风险等级由低到高。产品的风险评级仅供您参考，您应根据自身风险承受能力选择产品并承担投资风险。<br>**应法规要求，该基金类型变更为混合型证券投资基金，同时基金名称做出相应调整。因法律文件的变更涉及基金公司内部流程安排，本行会在基金公司完成文件变更后及时上传更新版本。基金名称更改公告请参考“基金公告”栏位。敬请理解。'
        },
        4027: {
            name: '交银施罗德稳健配置混合型证券投资基金',
            code: '519690',
            cate: '混合型',
            comp: '交银施罗德基金管理有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fund001.com/fund/519690/xsfy.shtml\');">点击查看</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fund001.com/fund/519690/xsfy.shtml\');">点击查看</a>',
            date: '2006年06月14日',
            risk: '4',
            rate: 'http://www.fund001.com/fund/519690/xsfy.shtml',
            share: '现金分红',
            intro: 'jiaoyinwenjian.htm',
            target: '本基金将坚持并不断深化价值投资的基本理念，充分发挥专业研究与管理能力，根据宏观经济周期和市场环境的变化，自上而下灵活配置资产，自下而上精选证券，有效分散风险，谋求实现基金财产的长期稳定增长。',
            feature: '本基金是一只混合型基金，属于证券投资基金产品中的中等风险品种，本基金的风险与预期收益处于股票型基金和债券型基金之间。本基金力争在有效分散风险的前提下谋求实现基金资产长期稳定增长。',
            standard: '65%×MSCI中国A股指数+35%×中证综合债券指数',
            range: '本基金的投资范围为具有良好流动性的金融工具，包括国内依法发行上市的股票、债券、现金、短期金融工具、权证、资产支持证券及法律法规或中国证监会允许基金投资的其他金融工具。其中债券投资的主要品种包括交易所和银行间两个市场的国债、金融债、企业债与可转换债。短期金融工具则包括到期日在一年以内的债券、债券回购、央行票据、银行存款、短期融资券等。如法律法规或监管机构以后允许基金投资的其它品种，基金管理人在履行适当程序后，可以将其纳入投资范围。<br>在正常市场情况下，基金的投资组合比例为：股票资产占基金资产净值的35%—95%；债券资产占基金资产净值的0%—60%；现金、短期金融工具、权证、资产支持证券以及中国证监会允许基金投资的其他证券品种占基金资产净值的5%-65%，其中基金保留的现金以及投资于一年期以内的政府债券的比例合计不低于基金资产净值的5%。在基金实际管理过程中，本基金具体配置比例由基金管理人根据中国宏观经济情况和证券市场的阶段性变化做主动调整，以求基金资产在各类资产的投资中达到风险和收益的最佳平衡，但比例不超出上述限定范围。在法律法规有新规定的情况下，基金管理人可对上述比例做适度调整。',
            tactics: '本基金的投资策略为：把握宏观经济和投资市场的变化趋势，根据经济周期理论动态调整投资组合比例，自上而下配置资产，自下而上精选证券，有效分散风险。<br>1、资产配置<br>本基金将采用“自上而下”的多因素分析决策支持系统，结合定性分析和定量分析进行大类资产的配置。具体而言，首先利用经济周期理论，对宏观经济的经济周期进行预测，在此基础上形成对不同资产市场表现的预测和判断，确定基金资产在各类别资产间的分配比例，并随着各类证券风险收益特征的相对变化，动态调整组合中各类资产的比例，以规避或分散市场风险，提高基金收益率。与传统的配置型基金不同，借鉴施罗德集团在平衡型基金方面成功的投资经验，本基金在资产配置方面有以下两大特点。<br>第一大特点是本基金管理人在进行资产配置的时候，除了考察各类资产的风险收益特征随市场环境的变化，同时关注资产之间相关性随时间的变化。对于配置型基金而言，投资于债券资产是为了分散股票资产投资的风险，以达到投资中风险和收益的最佳平衡。但是随着宏观经济环境和市场环境的变化，各类资产之间的相关性并不是一成不变的，最近一段时间的历史未必总能很好地反映未来的情况。因此，本基金管理人在“自上而下”进行资产配置的时候，除了考虑到不同经济周期下各类资产自身风险收益特征的变化，还会考察各类资产之间相关性随时间的变化，以经风险调整后的收益最大化为前提确定各类资产最优的配置比例，并随时间进行动态调整。<br>配置型基金灵活的资产配置使得基金管理人可以因时制宜，把握投资市场的变化趋势，在有效分散风险的同时获得长期稳定的投资回报。因此，正确把握投资市场的变化趋势对于配置型基金的成败至关重要。为了尽可能准确地把握投资市场变化的趋势，本基金管理人在对各种证券进行收益率预测的时候，一方面避免从短期的历史进行推断可能造成的错误，在合理范围内考察较长的历史区间，同时前瞻性地预测中长期经济环境的变化，并将该变化对证券未来收益的影响反映到对证券收益率的预期中去。这也是本基金的另一大特点。<br>具体操作中，本基金管理人采用经济周期理论下的资产配置模型，通过对宏观经济运行指标、利率和货币政策等相关因素的分析，对中国的宏观经济运行情况进行判断和预测，然后利用经济周期理论确定基金资产在各类别资产间的战略配置策略。<br>2、行业配置<br>本基金将通过对经济周期、产业环境、产业政策和行业竞争格局的分析和预测，确定宏观及行业经济变量的变动对不同行业的潜在影响，得出各行业的相对投资价值与投资时机，并据此对基金股票投资资产的行业分布进行动态调整。<br>3、股票选择<br>本基金综合运用施罗德集团的股票研究分析方法和经济周期理论精选股票构建成份股。具体分以下两个层次进行：<br>（1）品质筛选<br>筛选出在财务及管理品质上符合基本品质要求的上市公司。<br>（2）风格配置和组合优化<br>对备选股票进行风格分类，利用经济周期理论在不同风格类别的股票之间进行战略配置，同时结合组合优化模型以实现尽可能高的经风险调整后的收益。<br>4、债券投资<br>配置型基金中债券投资管理的目标是分散股票投资的市场风险，保持投资组合稳定收益和充分流动性，追求基金资产的长期增值。在目前中国债券市场处于制度与规则快速调整的阶段，对于债券投资组合的构建本基金管理人将采取自上而下的主动式管理，灵活运用各种消极和积极策略，寻找各种市场机会，获得超过市场水平的平均收益。消极债券投资的目标是在满足现金管理需要的基础上为基金资产提供稳定的收益。积极债券投资的目标是利用市场定价的无效率来获得低风险甚至是无风险的超额收益。<br>在全球经济的框架下，本基金管理人对宏观经济运行趋势及其引致的财政货币政策变化作出判断，运用数量化工具，对未来市场利率趋势及市场信用环境变化作出预测，通过组合优化进行合理的配置。<br>5、权证投资策略<br>本基金的权证投资以权证的市场价值分析为基础，配以权证定价模型寻求其合理估值水平，以主动式的科学投资管理为手段，充分考虑权证资产的收益性、流动性及风险性特征，通过资产配置、品种与类属选择，追求基金资产稳定的当期收益。<br>6、资产支持证券投资策略<br>本基金投资资产支持证券将综合运用久期管理、收益率曲线、个券选择和把握市场交易机会等积极策略，在严格控制风险的情况下，通过信用研究和流动性管理，选择风险调整后的收益高的品种进行投资，以期获得长期稳定收益。',
            notice: 'http://www.fund001.com/fund/519690/index.shtml',
            record: 'dailylmfnav',
            agreement: 'jiaoyinshiluodejijinhetong',
            investmentcontract: 'https://www.fund001.com/fund/519690/sxxpl.shtml',
            instruction: 'http://www.fund001.com/fund/519690/xsfy.shtml',
            protocol: 'jiaoyinshiluodejijintuoguanxieyi',
            remark: ''
        }
    },
    hk: {
        sdata: [{
            comp: 9,
            cate: 11,
            risk: 5,
            name: '摩根亚洲总收益债券基金<br>- PRC人民币对冲份额（累计）/ PRC人民币对冲份额（每月派息）-现金红利',
            id: 4025
        }, {
            comp: 9,
            cate: 12,
            risk: 5,
            name: '摩根太平洋证券基金<br>- PRC人民币对冲份额（累计）',
            id: 4026
        }, {
            comp: 9,
            cate: 12,
            risk: 5,
            name: '摩根亚洲股息基金<br>- PRC人民币对冲份额（累计）/ PRC人民币对冲份额（每月派息）',
            id: 4031
        }, {
            comp: 11,
            cate: 13,
            risk: 5,
            name: '施罗德亚洲高息股债基金<br>- M类别（人民币对冲累积）',
            id: 4028
        }, {
            comp: 9,
            cate: 12,
            risk: 5,
            name: '摩根亚洲增长基金',
            id: 4032
        }, {
            comp: 9,
            cate: 12,
            risk: 5,
            name: '摩根太平洋科技基金',
            id: 4033
        }],
        4025: {
            name: '摩根亚洲总收益债券基金<br>- PRC人民币对冲份额（累计）/ PRC人民币对冲份额（每月派息）-现金红利',
            isin: 'HK0000259686/ HK0000259694',
            code: '968000（累计）/968001（每月派息）',
            cate: '债券型',
            comp: '摩根基金（亚洲）有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968000/\');">点击查看</a> / <a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968001/\');">点击查看</a>',
            agency: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.cifm.com\');">上投摩根基金管理有限公司</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968000/\');">点击查看</a> / <a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968001/\');">点击查看</a>',
            date: '2005年1月18日 （该基金最早成立的份额类别的成立日期）',
            risk: '3',
            currency: '人民币',
            share: '不分红（累计）/现金分红（每月派息）-分红方式不可修改',
            rate: 'http://www.51fund.com/fund/968000/fee/#go',
            target: '本基金之投资目标为透过一个主要投资于亚洲债券及其他债券证券之积极管理组合，致力于提供具有竞争力的总高回报（包括资本增长及定息收益）。本基金亦可为投资目的而投资于衍生工具，例如期权、认股权证、信贷违约掉期及期货，并在管理人及投资管理人认为合适之有限情况下，于其投资组合内大量持有现金及现金为本的工具。',
            feature: '本基金为债券型基金，属于证券投资基金中的较低风险品种，其预期风险与预期收益高于货币基金，低于混合型基金和股票型基金',
            standard: '-',
            tactics: '本基金不受基准指数限制，可透过灵活的投资策略来捕捉亚洲债券市场的最佳投资概念，全力争取具有竞争力的总回报',
            notice: [{
                name: '累计款',
                url: 'http://www.51fund.com/fund/968000/announce/#go',
                title: ''
            }, {
                name: '派息款',
                url: 'http://www.51fund.com/fund/968001/announce/#go',
                title: '（基金单页、绩效表现、持仓明细、资产配置等相关公告可在此查询）'
            }],
            record: 'dailylmfnav',
            agreement: [{
                name: '累计款',
                url: 'https://www.cifm.com/fund/968000/',
                title: ''
            }, {
                name: '派息款',
                url: 'https://www.cifm.com/fund/968001/',
                title: ''
            }],
            instruction: [{
                name: '累计款',
                url: 'https://www.cifm.com/fund/968000/',
                title: ''
            }, {
                name: '派息款',
                url: 'https://www.cifm.com/fund/968001/',
                title: ''
            }],
            protocol: [{
                name: '累计款',
                url: 'https://www.cifm.com/fund/968000/',
                title: ''
            }, {
                name: '派息款',
                url: 'https://www.cifm.com/fund/968001/',
                title: ''
            }],
            remark: '*以上信息更新至2018年2月，仅供参考；各基金产品及基金公司信息由基金公司及其中国内地代理人提供，请以基金公司及其中国内地代理人公布之信息为准。'
        },
        4026: {
            name: '摩根太平洋证券基金<br>- PRC人民币对冲份额（累计）',
            isin: 'HK0000259660',
            code: '968010',
            cate: '股票型',
            comp: '摩根基金（亚洲）有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/96810\');">点击查看</a>',
            agency: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.cifm.com\');">上投摩根基金管理有限公司</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/96810\');">点击查看</a>',
            date: '1978年5月26日（该基金最早成立的份额类别的成立日期）',
            risk: '3',
            currency: '人民币',
            share: '不分红（累计）<br>-分红方式不可修改',
            rate: 'http://www.51fund.com/fund/968010/fee/#go',
            target: '本基金之投资政策为透过主要投资于亚太区（包括日本、澳大利亚及新西兰）企业之证券（ 证券通常指股票、存托凭证等权益类投资工具），为投资者提供长远资本增值。',
            feature: '本基金为股票型基金。',
            standard: '摩根士丹利综合亚太净回报指数',
            tactics: '本基金可为投资目的而投资于衍生工具，例如远期合约、期权、认股权证及期货，并在管理人及投资管理人认为合适之有限情况下，于投资组合内大量持有现金及以现金为本的工具。',
            notice: [{
                name: '点击查看',
                url: 'http://www.51fund.com/fund/968010/announce/#go',
                title: '（基金单页、绩效表现、持仓明细、资产配置等相关公告可在此查询）'
            }],
            record: 'dailylmfnav',
            agreement: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/96810',
                title: ''
            }],
            instruction: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/96810',
                title: ''
            }],
            protocol: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/96810',
                title: ''
            }],
            remark: '*以上信息更新至2018年2月，仅供参考；各基金产品及基金公司信息由基金公司及其中国内地代理人提供，请以基金公司及其中国内地代理人公布之信息为准。'
        },
        4031: {
            name: '摩根亚洲股息基金<br>- PRC人民币对冲份额（累计）/ PRC人民币对冲份额（每月派息）',
            isin: 'HK0000431798/ HK0000431806',
            code: '968044（累计）/968045（每月派息）',
            cate: '股票型',
            comp: '摩根基金（亚洲）有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968044\');">点击查看</a> / <a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968045\');">点击查看</a>',
            agency: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.cifm.com\');">上投摩根基金管理有限公司</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968044\');">点击查看</a> / <a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968045\');">点击查看</a>',
            date: '2013年5月31日 （该基金最早成立的份额类别的成立日期）',
            risk: '3',
            currency: '人民币',
            share: '不分红（累计）/现金分红（每月派息）-分红方式不可修改',
            rate: 'https://www.cifm.com/fund/968046/fee/#go',
            target: '本基金之投资目标为透过主要投资于亚太区（日本除外）内投资经理人预期会派发股息的公司之股票，以期提供收益及长期资本增长。基金所持有的此等股票将根据公司的过往派息纪录及公布，以及其长期资本增长潜力而挑选。基金可以辅助投资方式投资于在亚太区（日本除外）注册或投资的房地产投资信托。',
            feature: '本基金为股票型基金',
            standard: 'MSCI综合亚太（不包括日本）净回报指数',
            tactics: '本基金可为投资目的而投资于衍生工具，例如期权、认股权证及期货，并在经理人及投资经理人认为合适之有限情况下（例如以现金管理为目的），于投资组合内持有大量现金及以现金为本的工具。',
            notice: [{
                name: '累计款',
                url: 'https://www.cifm.com/fund/968044/announce/#go',
                title: ''
            }, {
                name: '派息款',
                url: 'https://www.cifm.com/fund/968045/announce/#go',
                title: '（基金单页、绩效表现、持仓明细、资产配置等相关公告可在此查询）'
            }],
            record: 'dailylmfnav',
            agreement: [{
                name: '累计款',
                url: 'https://www.cifm.com/fund/968044',
                title: ''
            }, {
                name: '派息款',
                url: 'https://www.cifm.com/fund/968045',
                title: ''
            }],
            instruction: [{
                name: '累计款',
                url: 'https://www.cifm.com/fund/968044',
                title: ''
            }, {
                name: '派息款',
                url: 'https://www.cifm.com/fund/968045',
                title: ''
            }],
            protocol: [{
                name: '累计款',
                url: 'https://www.cifm.com/fund/968044',
                title: ''
            }, {
                name: '派息款',
                url: 'https://www.cifm.com/fund/968045',
                title: ''
            }],
            remark: '*以上信息更新至2019年2月，仅供参考；各基金产品及基金公司信息由基金公司及其中国内地代理人提供，请以基金公司及其中国内地代理人公布之信息为准。'
        },
        4028: {
            name: '施罗德亚洲高息股债基金<br>- M类别（人民币对冲累积）',
            isin: 'HK0000276136',
            code: '968013',
            cate: '混合型',
            comp: '施罗德投资管理（香港）有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fund001.com/web_north/968013/xgproductdtfundsy.shtml\');">点击查看</a>',
            agency: '<a href="javascript:;" onclick="return setOutlingHref(\'http://www.fund001.com/web_north/968013/xgproductdtfundsy.shtml\');">点击查看</a>',
            manager: '主要投资组合经理包括来自亚洲多元资产团队的Patrick Brenner以及Seung Ju Kim，来自亚洲股票团队的Manish Bhatia以及来自亚洲固定收益团队的Angus Hui',
            date: '1978年5月26日 （该基金最早成立的份额类别的成立日期）',
            risk: '3',
            currency: '人民币',
            share: '不分红（累计）<br>-分红方式不可修改',
            rate: 'http://www.fund001.com/web_north/968013/xgproductdtfundsy.shtml',
            target: '主要通过投资于亚洲股票和亚洲固定收益证券，以期提供中长期收益及资本增值。',
            feature: '本基金为股债混合型基金',
            standard: '-',
            tactics: '本基金主要通过投资于一篮子提供高收益率和持续派发股息的亚洲公司的权益性证券，包括房地产投资信托基金以及由亚洲各地政府、政府机构、国际组织及企业发行人所发行的并提供高收益的债券和其他固定或浮动利率证券（该等证券在购入时或购入后可能是投资级别或投资级别以下的证券），以达到投资目标。本基金可大量投资于评级低于投资级别或未获评级的债券和债务证券。如基金管理人认为合适，本基金可有限度地通过交易所交易基金及╱或类似工具间接投资于其他种类的资产，包括但不限于非亚洲证券、商品（包括能源、金属和农产品）。<br>本基金将积极地在亚洲股票、亚洲固定收益证券、其他种类的资产和现金之间进行投资配置，以达到本基金的目标。本基金将运用周期性方针配置资产，即资产将依经济周期的四个阶段——复苏、膨胀、放缓和衰退，按基础和定量因素如资产种类估值、宏观经济数据和流动性调整资产组合。现金将被视为独立的资产种类，如有需要，在不利市场情况时将被用于控制下跌风险。',
            notice: [{
                name: '点击查看',
                url: 'http://www.fund001.com/xgzq2016/index.shtml',
                title: '（基金单页、绩效表现、持仓明细、资产配置等相关公告可在此查询）'
            }],
            record: 'dailylmfnav',
            agreement: [{
                name: '点击查看',
                url: 'http://www.fund001.com/web_north/968013/xgproductdtfundsy.shtml',
                title: ''
            }],
            instruction: [{
                name: '点击查看',
                url: 'http://www.fund001.com/web_north/968013/xgproductdtfundsy.shtml',
                title: ''
            }],
            protocol: [{
                name: '点击查看',
                url: 'http://www.fund001.com/web_north/968013/xgproductdtfundsy.shtml',
                title: ''
            }],
            remark: '*以上信息更新至2017年7月，仅供参考；各基金产品及基金公司信息由基金公司及其中国内地代理人提供，请以基金公司及其中国内地代理人公布之信息为准。'
        },

        4032: {
            name: '摩根亚洲增长基金<br>- PRC人民币对冲份额（累计）',
            isin: 'HK0000584075',
            code: '968072',
            cate: '股票型',
            comp: '摩根基金（亚洲）有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968072/\');">点击查看</a> ',
            agency: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/\');">上投摩根基金管理有限公司</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968072/\');">点击查看</a> ',
            date: '2007年5月14日（该基金最早成立的份额类别的成立日期）',
            risk: '4',
            currency: '人民币',
            share: '不分红（累计）-分红方式不可修改',
            rate: 'https://www.cifm.com/fund/968072/fee/#go',
            target: '本基金的投资目标是为投资者提供长远资本增值，为实现此目标，本基金将其至少70%的总资产净值投资于其主要业务受惠于亚洲经济体系的增长或与其有关的公司股票。',
            feature: '本基金属于股票型基金产品，预期风险和收益水平高于混合型基金、债券型基金和货币市场基金，属于较高风险收益水平的基金。',
            standard: '摩根士丹利综合亚洲（不包含日本）净回报指数',
            tactics: '本基金在任何行业可投资的总资产净值的比例不受任何限制, 其可投资的公司市值亦不受任何限制。本基金于中国A股及B股的总投资（直接及间接）不可超过其总资产净值的10%。该有关中国A股及／或B股的投资政策未来如有改变，管理人将向内地投资者发出一个月的事先通知，而销售文件将作出相应更新。 <br> 本基金亦可出于投资目的而投资于衍生工具，例如期权、认股权证及期货。本基金将有限度地投资于以人民币计价的相关投资标的。',
            notice: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/968072/',
                title: '（基金单页、绩效表现、持仓明细、资产配置等相关公告可在此查询）'
            }],
            record: 'dailylmfnav',
            agreement: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/968072/',
                title: ''
            }],
            instruction: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/968072/',
                title: ''
            }],
            protocol: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/968072/',
                title: ''
            }],
            remark: '*以上信息更新至2020年12月，仅供参考；各基金产品及基金公司信息由基金公司及其中国内地代理人提供，请以基金公司及其中国内地代理人公布之信息为准。'
        },



        4033: {
            name: '摩根太平洋科技基金<br>- PRC人民币对冲份额（累计）',
            isin: 'HK0000555752',
            code: '968061',
            cate: '股票型',
            comp: '摩根基金（亚洲）有限公司',
            trustee: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968061/\');">点击查看</a> ',
            agency: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/\');">上投摩根基金管理有限公司</a>',
            manager: '<a href="javascript:;" onclick="return setOutlingHref(\'https://www.cifm.com/fund/968061/\');">点击查看</a> ',
            date: '1997年8月15日（该基金最早成立的份额类别的成立日期）',
            risk: '4',
            currency: '人民币',
            share: '不分红（累计）-分红方式不可修改',
            rate: 'https://www.cifm.com/fund/968061/fee/#go',
            target: '本基金的投资政策为通过一个主要投资于太平洋地区（包括日本）科技公司（包括但不限于科技、媒体及电讯有关的公司）证券【1】的投资组合，为投资者提供长远资本增值。本基金亦可为投资目的而投资于衍生工具，例如远期合约、期权、认股权证及期货，并在管理人及投资管理人认为合适的有限情况下，在其投资组合内持有大量现金以及现金等价物。（【1】证券通常指股票、存托凭证等权益类投资工具）',
            feature: '本基金属于股票型基金产品，预期风险和收益水平高于混合型基金、债券型基金和货币市场基金，属于较高风险收益水平的基金。',
            standard: '不设比较基准',
            tactics: '本基金可投资的公司市值不受任何限制。<br> 本基金亦可出于投资目的而投资于衍生工具，例如远期合约、期权、认股权证及期货。',
            notice: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/968061/',
                title: '（基金单页、绩效表现、持仓明细、资产配置等相关公告可在此查询）'
            }],
            record: 'dailylmfnav',
            agreement: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/968061/',
                title: ''
            }],
            instruction: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/968061/',
                title: ''
            }],
            protocol: [{
                name: '点击查看',
                url: 'https://www.cifm.com/fund/968061/',
                title: ''
            }],
            remark: '*以上信息更新至2020年12月，仅供参考；各基金产品及基金公司信息由基金公司及其中国内地代理人提供，请以基金公司及其中国内地代理人公布之信息为准。'
        },
    }
};
var company = {
    ch: {
        2: {
            name: '景顺长城基金管理有限公司',
            legal: '赵如冰',
            date: '2003年6月12日',
            capital: '13,000万元',
            address: '深圳市福田区中心四路1号嘉里建设广场第一座21层',
            zipcode: '518048',
            tel: '400-888-8606',
            fax: '0755-22381315',
            email: 'investor@igwfmc.com',
            url: 'www.igwfmc.com',
            history: '经中国证监会证监基金字[2003]76号文批准设立的证券投资基金管理公司，由长城证券有限责任公司、景顺资产管理有限公司、开滦集团有限责任公司、大连实德集团有限公司共同发起设立，并于2003年6月9日获得开业批文，各家出资比例分别为33%、33%、17%、17%。<br>2005年6月，长城证券有限责任公司受让开滦（集团）有限责任公司所持的公司16％的股权，景顺资产管理有限公司受让大连实德集团有限公司持有的公司16％的股权。受让完成后，公司注册资本保持不变，股东及出资比例分别为长城证券有限责任公司49%、景顺资产管理有限公司49%、开滦（集团）有限责任公司1%和大连实德集团有限公司1%。2006年2月，注册资本由一亿元增加为人民币一亿三千万元，增资后原股东持股比例保持不变。<br>注：基金管理人与股东之间实行业务隔离制度，股东并不直接参与基金财产的投资运作。',
            remark: '资料来源：景顺长城基金管理有限公司，资料截止至2017年11月。<br>各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        },
        3: {
            name: '泰达宏利基金管理有限公司',
            legal: '弓劲梅',
            date: '2002年6月6日',
            capital: '18,000万元',
            address: '北京市西城区金融大街7号英蓝国际金融中心南楼三层',
            zipcode: '100033',
            tel: '400-698-8888',
            fax: '010-66577666',
            email: 'irm@mfcteda.com',
            url: 'www.mfcteda.com',
            history: '经中国证监会证监基字[2002]37号文批准设立的基金管理公司，注册资本为一亿元人民币。<br>2003年9月8日经中国证监会批准，荷兰银行正式参股湘财合丰基金管理公司。中国证监会批准（证监基金字[2003]153号文），将本公司名称变更为湘财荷银基金管理有限公司。<br>2004年报中国证监会核准（证监基金字[2004]122号文），山东鑫源控股有限公司将所持有的本公司30%的股权转让给公司现有股东湘财证券有限责任公司。<br>经湘财荷银基金管理有限公司2004年第三次股东会审议通过，并报中国证监会批准（证监基金字[2005]21号文），荷兰银行有限公司将所持有的本公司33%的股权转让给荷银投资管理（亚洲）有限公司。<br>2006年4月北方国际信托取代湘财证券成为第一大股东，持有股权51%，原外方股东荷银投资管理（亚洲）有限公司则增持至49%，更名为泰达荷银基金管理有限公司。<br>2006年10月，注册资本由人民币一亿增加为人民币一亿八千万元，公司现有股东原持股比例保持不变。<br>2009年度第五次股东会审议通过并报中国证监会批准（证监许可[2010]166号文），股东及持股比例变为：北方国际信托投资股份有限公司51%；宏利资产管理（香港）有限公司49%。公司名称由“泰达荷银基金管理有限公司”变更为“泰达宏利基金管理有限公司”。<br>注：基金管理人与股东之间实行业务隔离制度，股东并不直接参与基金财产的投资运作。',
            remark: '资料来源：泰达宏利基金管理有限公司，资料截止至2017年11月。<br>各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        },
        4: {
            name: '富国基金管理有限公司',
            legal: '薛爱东',
            date: '1999年04月13日',
            capital: '18000万元',
            address: '上海市浦东新区世纪大道8号上海国金中心二期16-17层',
            zipcode: '200120',
            tel: '400-888-0688',
            fax: '021-20361616',
            email: 'public@fullgoal.com.cn',
            url: 'www.fullgoal.com.cn',
            history: '富国基金于1999年在北京成立，是经中国证监会批准设立的首批十家基金管理公司之一。2003年加拿大蒙特利尔银行参股，富国基金成为国内首批十家基金公司中第一家实现外资参股的基金公司。公司注册资本为1.8亿元人民币，四大股东中，海通证券、申银万国证券、加拿大蒙特利尔银行分别出资27.775%，山东省国际信托投资公司出资16.675%。公司现有员工323人，其中 61.8%以上具有硕士以上学历。总部设于上海，在北京、广州、成都设有分公司，并设有富国资产管理（香港）有限公司。根据银河数据显示，截至2015年12月31日公司共管理公募基金68只，基金资产1924亿元，市场排名第13位；长期资产（剔除货币与短期理财）1701亿元，市场排名第5位。<br>注：基金管理人与股东之间实行业务隔离制度，股东并不直接参与基金财产的投资运作。',
            remark: '资料来源：富国基金管理有限公司，资料截止至2017年11月。<br>各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        },
        5: {
            name: '上投摩根基金管理有限公司',
            legal: '陈开元',
            date: '2004年05月12日',
            capital: '25,000万元',
            address: '上海市浦东富城路99号震旦国际大楼20层',
            zipcode: '200120',
            tel: '400-889-4888',
            fax: '021-20628400',
            email: 'services@cifm.com',
            url: 'www.51fund.com',
            history: '上投摩根基金管理有限公司(China International Fund Management Co., Ltd.)成立于2004年5月。公司现阶段主要致力于设立和管理证券投资基金，今后将在法律法规许可的范围内提供多元化的资产管理服务，包括社保基金、企业年金以及为企业提供个性化的理财服务。',
            remark: '资料来源：上投摩根基金管理有限公司，资料截止至2017年11月。各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        },
        6: {
            name: '海富通基金管理有限公司',
            legal: '张文伟',
            date: '2003年04月01日',
            capital: '人民币1.5亿元',
            address: '上海市浦东新区陆家嘴花园石桥路66号东亚银行金融大厦36-37层',
            zipcode: '200120',
            tel: '400-884-0099',
            fax: '021-50479997',
            email: 'info@hftfund.com',
            url: 'www.hftfund.com',
            history: '海富通基金管理有限公司成立于2003年4月，是中国首批获准成立的中外合资基金管理公司。<br>从2003年8月开始，海富通先后募集成立了31只公募基金。截至2015年6月30日，海富通管理的公募基金资产规模为451亿元人民币。<br>作为国家人力资源和社会保障部首批企业年金基金投资管理人，截至2015年6月30日，海富通为近80家企业超过392亿元的企业年金基金担任了投资管理人。作为首批特定客户资产管理业务资格的基金管理公司，截至2015年6月30日，海富通旗下专户理财管理资产规模超过125亿元。2010年12月，海富通基金管理有限公司被全国社会保障基金理事会选聘为境内委托投资管理人。2012 年9 月，中国保监会公告确认海富通基金为首批保险资金投资管理人之一。<br>2004年末开始，海富通为QFII（合格境外机构投资者）及其他多个海内外投资组合担任投资咨询顾问，截至2015年6月30日，投资咨询及海外业务规模逾144亿元人民币。2011年12月，海富通全资子公司——海富通资产管理（香港）有限公司获得证监会核准批复RQFII（人民币合格境外机构投资者）业务资格，能够在香港筹集人民币资金投资境内证券市场。2012年2月，海富通资产管理（香港）有限公司已募集发行了首只RQFII产品。<br>2012年3月，国内权威财经媒体《中国证券报》等授予海富通基金管理有限公司“中国基金业金牛基金管理公司”大奖，《证券时报》授予海富通精选混合基金“2011年中国基金业明星奖—五年持续回报平衡混合型明星基金”荣誉。2013年4月，《上海证券报》授予海富通精选混合基金2012年“金基金”奖——分红基金奖。<br>海富通同时还在不断践行其社会责任。公司自2008年启动“绿色与希望-橄榄枝公益环保计划”，针对汶川震区受灾学校、上海民工小学、安徽老区小学进行了物资捐赠，向内蒙古库伦旗捐建了环保公益林。几年来，海富通的公益行动进一步升级，持续为上海民工小学学生捐献生活物资，并向安徽农村小学捐献图书室。此外，海富通还积极推进投资者教育工作，推出了以“幸福投资”为主题和特色的投资者教育活动，向投资者传播长期投资、理性投资的理念。',
            remark: '资料来源：海富通基金管理有限公司，资料截止至2017年11月。各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        },
        7: {
            name: '博时基金管理有限公司',
            legal: '张光华',
            date: '1998年07月13日',
            capital: '2.5亿元',
            address: '广东省深圳市福田区深南大道7088号招商银行大厦29层',
            zipcode: '518040',
            tel: '95105568',
            fax: '0755-83195140',
            email: 'service@bosera.com',
            url: 'www.bosera.com',
            history: '博时基金管理有限公司成立于1998年7月13日，是中国内地首批成立的五家基金管理公司之一，致力为海内外各类机构和个人投资者提供专业、全面的资产管理服务。博时基金总部设在深圳，在北京、上海、郑州、沈阳、成都设有分公司，同时拥有博时基金（国际）有限公司和博时资本管理有限公司两家全资子公司。博时基金公司的股东为招商证券股份有限公司、中国长城资产管理公司、上海汇华实业有限公司、天津港（集团）有限公司、上海盛业股权投资基金有限公司、广厦建设集团有限责任公司。博时基金公司的经营范围包括基金募集、基金销售、资产管理和中国证监会许可的其他业务，是一家为客户提供专业投资服务的资产管理机构。',
            remark: '资料来源：博时基金管理有限公司，资料截止至2017年11月。各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        },
        8: {
            name: '华夏基金管理有限公司',
            legal: '杨明辉',
            date: '1998年04月09日',
            capital: '2.38亿元',
            address: '北京市西城区月坛南街1号院7号楼',
            zipcode: '100045',
            tel: '010-88066801',
            fax: '010-63136700',
            email: 'service@chinaamc.com',
            url: 'http://www.chinaamc.com/',
            history: '华夏基金管理有限公司成立于1998年4月9日，是经中国证监会批准成立的首批基金管理公司之一，注册地为北京，注册资本2.38亿元，股东为中信证券（62.2%）、南方工业资产（7.8%）、山东省农村经济开发投资公司（10%）、POWER CORPORATION OF CANADA（10%）、青岛海鹏科技投资有限公司（10%）。截至2016年3月31日，公司管理基金资产净值为5956亿，是国内资产管理规模最大的基金公司之一，公司服务机构客户35000余户，服务公众持有人2000万户，累计分红超1200亿元。华夏基金9次获得《中国证券报》评选的“年度金牛基金公司奖”、9次获得《上海证券报》评选的“中国最佳基金公司TOP大奖”、5次被《亚洲资产管理》评为“中国年度最佳基金公司奖”等。',
            remark: '资料来源：华夏基金管理有限公司。资料截止至2017年11月。各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        },
        10: {
            name: '交银施罗德基金管理有限公司',
            legal: '于亚利',
            date: '2005年08月04日',
            capital: '2亿元人民币',
            address: '上海市浦东新区世纪大道8号国金中心二期21-22楼',
            zipcode: '200120',
            tel: '021-61055793',
            fax: '021-61055034',
            email: 'services@jysld.com',
            url: 'www.fund001.com，www.bocomschroder.com',
            history: '交银施罗德基金管理有限公司成立于2005年8月4日，经中国证监会证监基金字[2005]128号文批准设立，注册地为上海，注册资本2亿元，股东为交通银行股份有限公司（65%）、施罗德投资管理有限公司（30%）、中国国际海运集装箱（集团）股份有限公司（5%）。截至2017年6月30日，公司管理公募基金资产净值为882亿。',
            remark: '资料来源：交银施罗德管理有限公司。资料截止至2017年11月。各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        },
        12: {
            name: '中欧基金管理有限公司',
            legal: '窦玉明',
            date: '2006年07月19日',
            capital: '2.2亿元人民币',
            address: '中国上海市浦东新区陆家嘴环路333号5层',
            zipcode: '200120',
            tel: '400-700-9700（免长途话费）021-68609700',
            fax: '021-33830351',
            email: 'Marketservice@zofund.com',
            url: 'www.zofund.com',
            history: '中欧基金管理有限公司成立于2006年，是国内首批员工持股的公募基金管理公司之一，核心员工成为公司重要股东。在领先的治理结构下，客户、公司员工与股东的利益紧密捆绑，形成合力，共同打造“聚焦长期业绩的主动投资精品店”。中欧基金为个人投资者和专业机构投资者提供了卓越的长期投资业绩和一流服务。截至2020年12月31日，中欧基金公司管理规模已超5000亿元，其中公募基金规模4153亿，专户规模860亿。',
            remark: '资料来源：中欧基金管理有限公司。资料截止至2020年12月。各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        }
    },
    hk: {
        9: {
            name: '摩根基金（亚洲）有限公司',
            history: '摩根资产管理有限公司，是隶属于摩根大通集团旗下，是全球最大的资产管理公司之一。集团在全球共驻有940位卓越投资专才，在全球范围内管理的资产总规模超过10万亿人民币。（截至2015年３月31日）对亚太、欧洲及美国三大区域的投资形势均了如指掌，让投资者尽享雄厚环球网络的优势。<br>摩根在全球各地均拥有投资专才，积极进行第一手研究及实地公司考察，率先发掘长线潜力优厚及应变灵活的公司作投资。多年来，摩根秉承这种投资哲学所取得的成绩有目共睹，并荣获多项大奖嘉许及独立分析机构高度评价。',
            innerintro: '上投摩根基金管理有限公司成立于2004年5月，总部位于上海，注册资本2.5亿元人民币。其中上海国际信托出资占比51%，摩根大通旗下摩根资产管理出资占比49%。<br>集摩根资产管理150年享誉全球的专业资产管理经验，汇上海国际信托扎根本土的悠久品牌信誉，上投摩根传承中外股东精粹，致力于设立和管理证券投资基金，为不同类型的投资者提供多元化、国际领先的资产管理服务，成为值得信赖的长期合作伙伴。<div style="padding-top:10px;">（注：摩根、JP摩根或摩根资产管理为J.P. Morgan Asset Management的中文名称，是本公司的外方股东。本公司与股东实行业务隔离，但股东不直接参与基金的投资运作。）</div>',
            remark: '*资料来源：摩根基金（亚洲）有限公司，上投摩根基金管理公司，资料截止至2017年11月。各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        },
        11: {
            name: '施罗德投资管理（香港）有限公司',
            history: '施罗德投资是一家独立的、纯粹的全球资产管理公司，拥有超过200年的投资历史。我们是在伦敦证券交易所上市的最大的资产管理公司之一。我们的业务是资产管理，我们的目标与客户的目标完全一致——创造长期价值。施罗德香港是施罗德集团的全资子公司，自1971年起在香港经营业务。施罗德投资在香港拥有超过40年投资经验，并已为香港客户管理平衡型投资组合长达40年。',
            innerintro: '交银施罗德是中国第一批银行背景基金公司之一，也是众多中外合资基金公司中的佼佼者。由拥有百年历史的交通银行、二百年投资经验积累的施罗德投资管理有限公司、以及全球集装箱行业的佼佼者中国国际海运集装箱（集团）股份有限公司强强联合，共同发起设立。<br>成立至今，一直秉承“诚信百年、专业理财”的经营宗旨，以诚信和专业作为公司的立身之本，以“稳健源自前瞻”作为公司的核心价值主张，打造“专业、纪律、协作”的团队，营造“激情、包容、关爱”的企业文化，致力于在策略上远见，投资上前瞻，服务上领先，为投资人提供多元化的、全球视野的、专业独具的理财产品和投资服务。公司成立至今已获得包括“金牛奖”在内的众多荣誉，得到了普通投资者和各机构的广泛关注和认可。<br>目前，公司旗下共管理着包括股票型基金、混合型基金、债券型基金、QDII基金以及ETF基金等类型。同时，作为国内专户理财业务的“先驱者”，公司在专户理财、投资咨询业务方面上也积极开拓业务，较为成功地管理着数只专户理财产品，有力地推动了公司业务的多元化发展。<br>站在巨人肩上，我们将秉承百年传承的诚信，兼收千锤百炼的专业方法，勤勉尽责，规范运作，力争成为业绩出众、服务一流、深受投资者青睐的基金管理公司。',
            remark: '资料来源：*资料来源：施罗德基金（香港）有限公司，交银施罗德基金管理公司，资料截止至2017年11月。各基金产品及基金公司等相关信息请以基金公司公布之信息为准。'
        }
    }
};
